(()=>{
const D=window.ALFRED_ASSESSMENT||{}, A=window.ALFRED_ACADEMIC||{}, $=(s,r=document)=>r.querySelector(s);
const EVIDENCE_REVISION=String(D.meta?.evidenceRevision||D.meta?.version||'16.2');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='alfred-u-progress-v2';
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return {}}}
function weekObj(v){return typeof v==='string'?{mastery:v,assessments:{},labs:{}}:{...(v||{}),mastery:v?.mastery||'',assessments:v?.assessments||{},labs:v?.labs||{}}}
function blank(){return {v:2,q:[0,0],legacyQ:[0,0],sec:0,r:{},k:{},d:{},trend:[],firstAt:0,lastAt:0}}
function pairAdd(map,key,c,t){const x=map[key]||[0,0];x[0]+=Number(c||0);x[1]+=Number(t||0);map[key]=x}
function derived(a){
 if(a?.analytics&&String(a.analytics.bankRevision||'')!==EVIDENCE_REVISION){const old=a.analytics;return {...blank(),q:[...(old.q||[0,0])],legacyQ:[...(old.q||[0,0])],sec:Number(old.sec||0),trend:[...(old.trend||[])],firstAt:old.firstAt||0,lastAt:old.lastAt||0};}
 if(a?.analytics?.v===2&&!a.analytics.s)return a.analytics;
 const x=blank();
 if(a?.analytics?.v===2&&a.analytics.s){const old=a.analytics;x.q=[Number(old.q?.[0]||0),Number(old.q?.[1]||0)];x.legacyQ=[...(old.legacyQ||[0,0])];x.sec=Number(old.sec||0);x.r={...(old.r||{})};x.k={...(old.k||{})};x.d={...(old.d||{})};x.trend=[...(old.trend||[])];x.firstAt=Number(old.firstAt||0);x.lastAt=Number(old.lastAt||0);return x}
 if(a?.analytics?.v===1){const old=a.analytics;x.q=[Number(old.q?.[0]||0),Number(old.q?.[1]||0)];x.legacyQ=[...x.q];x.sec=Number(old.sec||0);x.trend=[...(old.trend||[])];x.firstAt=Number(old.firstAt||0);x.lastAt=Number(old.lastAt||0);return x}
 [...(a?.attempts||[])].sort((u,v)=>Date.parse(u.at||0)-Date.parse(v.at||0)).forEach(at=>{const ts=Date.parse(at.at||'')||0,c=Number(at.correct||0),t=Number(at.total||0);x.q[0]+=c;x.q[1]+=t;x.legacyQ[0]+=c;x.legacyQ[1]+=t;x.sec+=Number(at.seconds||0);if(ts){x.firstAt=x.firstAt||ts;x.lastAt=Math.max(x.lastAt,ts);x.trend.push([ts,Number(at.pct||0)])}});x.trend=x.trend.slice(-8);return x;
}
function records(p){const out=[];Object.entries(p.events||{}).forEach(([id,e])=>{if(e?.assessments?.lesson)out.push({type:'Optional Week Practice',key:`lesson:${id}`,a:e.assessments.lesson})});Object.entries(p.weeks||{}).forEach(([week,raw])=>{const w=weekObj(raw);Object.entries(w.assessments||{}).forEach(([key,a])=>{const kind=key.split(':')[0],label=kind==='lab'?'Lab Check':kind==='week'?'Weekly Review':kind==='major'?'Major Assessment':'Assessment';out.push({type:label,key:`${week}:${key}`,a})})});return out}
function stdRow(g,id){return g.std[id]||=( {c:0,t:0,wc:0,wt:0,high:0,sessions:0,last:0,lastC:0,lastT:0,streak:0,legacy:0} )}
function aggregate(){
 const p=load(),recs=records(p),g={q:[0,0],legacyQ:[0,0],sec:0,r:{},k:{},d:{},types:{},trend:[],std:{},attempts:0,records:recs.length};
 recs.forEach(rec=>{const x=derived(rec.a),validC=Math.max(0,Number(x.q?.[0]||0)-Number(x.legacyQ?.[0]||0)),validT=Math.max(0,Number(x.q?.[1]||0)-Number(x.legacyQ?.[1]||0));g.q[0]+=Number(x.q?.[0]||0);g.q[1]+=Number(x.q?.[1]||0);g.legacyQ[0]+=Number(x.legacyQ?.[0]||0);g.legacyQ[1]+=Number(x.legacyQ?.[1]||0);g.sec+=Number(x.sec||0);pairAdd(g.types,rec.type,validC,validT);Object.entries(x.r||{}).forEach(([k,v])=>pairAdd(g.r,k,v[0],v[1]));Object.entries(x.k||{}).forEach(([k,v])=>pairAdd(g.k,k,v[0],v[1]));Object.entries(x.d||{}).forEach(([k,v])=>pairAdd(g.d,k,v[0],v[1]));(x.trend||[]).forEach(v=>g.trend.push([Number(v[0]||0),Number(v[1]||0),rec.type]));g.attempts+=Number(rec.a?.attemptCount||(rec.a?.attempts||[]).length||0);
   // Unmigrated older records only contribute a Revalidation Needed marker, never validated confidence.
   if(String(rec.a?.analytics?.bankRevision||'')!==EVIDENCE_REVISION&&rec.a?.analytics?.s)Object.entries(rec.a.analytics.s).forEach(([sid,v])=>{stdRow(g,sid).legacy+=Number(v[1]||0)});
   else if(rec.a?.analytics?.v===2&&rec.a.analytics.s)Object.entries(rec.a.analytics.s).forEach(([sid,v])=>{const z=stdRow(g,sid),wt=Number(v[8]||0);if(wt){z.c+=Number(v[0]||0);z.t+=Number(v[1]||0);z.sessions+=Number(v[2]||0);z.wc+=Number(v[7]||0);z.wt+=wt;z.high+=Number(v[9]||0);const last=Number(v[5]||0);if(last>=z.last){z.last=last;z.lastC=Number(v[3]||0);z.lastT=Number(v[4]||0);z.streak=Number(v[6]||0)}}else z.legacy+=Number(v[1]||0)});
   else if(!rec.a?.analytics)(rec.a?.attempts||[]).forEach(at=>Array.isArray(at?.s)&&at.s.forEach(v=>{const sid=v?.[0],n=Number(v?.[2]||0);if(sid&&n)stdRow(g,sid).legacy+=n}));
 });
 // Current reviewed-bank category/domain shards are the authoritative lifetime competency rollup.
 Object.values(p.analytics||{}).forEach(sh=>{Object.entries(sh?.legacyS||{}).forEach(([sid,v])=>stdRow(g,sid).legacy+=Number(v[1]||0));if(String(sh?.bankRevision||'')!==EVIDENCE_REVISION){Object.entries(sh?.s||{}).forEach(([sid,v])=>stdRow(g,sid).legacy+=Number(v[1]||0));Object.entries(sh?.l||{}).forEach(([sid,n])=>stdRow(g,sid).legacy+=Number(n||0));return;}Object.entries(sh?.s||{}).forEach(([sid,v])=>{const z=stdRow(g,sid);z.c+=Number(v[0]||0);z.t+=Number(v[1]||0);z.sessions+=Number(v[2]||0);z.wc+=Number(v[7]||0);z.wt+=Number(v[8]||0);z.high+=Number(v[9]||0);const last=Number(v[5]||0);if(last>=z.last){z.last=last;z.lastC=Number(v[3]||0);z.lastT=Number(v[4]||0);z.streak=Number(v[6]||0)}});Object.entries(sh?.l||{}).forEach(([sid,n])=>{stdRow(g,sid).legacy+=Number(n||0)})});
 Object.values(g.std).forEach(z=>{z.pct=z.t?Math.round(z.c/z.t*100):0;z.validPct=z.wt?Math.round(z.wc/z.wt*100):0;const ok=z.last&&z.lastC===z.lastT,days=ok?(z.streak>=3?45:z.streak===2?21:7):2;z.due=z.last?z.last+days*86400000:0});
 g.trend.sort((a,b)=>a[0]-b[0]);let virtual=0,physical=0,academic=0;Object.values(p.weeks||{}).forEach(raw=>{const w=weekObj(raw);Object.values(w.labs||{}).forEach(l=>{if(l.virtual)virtual++;if(l.physical)physical++;if(l.virtual||l.physical)academic++})});g.labs={virtual,physical,academic,total:(A.labs||[]).length||24};g.localBytes=new Blob([JSON.stringify(p)]).size;return g;
}
const G=aggregate(),stdIndex=new Map([...D.cetaStandards,...D.careerStandards].map(s=>[s.id,s])),BANK={};(D.questions||[]).filter(q=>q?.masteryEvidence!==false&&q?.difficulty!=='Orientation').forEach(q=>(q.standards||[]).forEach(id=>BANK[id]=(BANK[id]||0)+1));
function confidence(z,id){if(!z||!z.wt)return 0;const acc=z.wc/z.wt,evid=Math.min(1,z.wt/8)*.60+Math.min(1,z.sessions/3)*.40,age=z.last?Math.max(0,(Date.now()-z.last)/86400000):999,rec=age<=7?1:age<=21?.9:age<=45?.75:age<=90?.55:.35,cons=Math.min(1,(z.streak||0)/3),breadth=Math.min(1,(BANK[id]||0)/2),raw=Math.round(100*(acc*.50+evid*.20+rec*.10+cons*.10+breadth*.10));return raw}
function state(id){const s=stdIndex.get(id),z=G.std[id];if(s?.assessable===false)return 'Reference';if(!z||!z.wt)return z?.legacy?'Revalidation Needed':'Not Introduced';if(z.due&&z.due<=Date.now())return 'Retention Due';const cf=confidence(z,id);if(z.wt<2||z.sessions<2)return 'Learning';if((BANK[id]||0)<2)return 'Evidence Limited';if(cf>=85&&z.validPct>=85&&z.streak>=3&&z.sessions>=3)return 'Mastered';if(cf>=72&&z.validPct>=80&&z.sessions>=2)return 'Proficient';return 'Developing'}
function pairPct(v){return v&&v[1]?Math.round(v[0]/v[1]*100):null}
function assessable(list){return list.filter(s=>s.assessable!==false)}
function readiness(list){const ss=assessable(list);if(!ss.length)return 0;return Math.round(ss.reduce((sum,s)=>sum+confidence(G.std[s.id],s.id),0)/ss.length)}
function coverage(list){const ss=assessable(list),n=ss.filter(s=>G.std[s.id]?.wt).length;return {n,total:ss.length,pct:ss.length?Math.round(n/ss.length*100):0}}
function domainStats(track){const standards=track==='CETa'?D.cetaStandards:D.careerStandards,cats=track==='CETa'?D.cetaCategories:D.careerDomains;return cats.map(cat=>{const ss=assessable(standards.filter(s=>s.category===cat.id)),c=ss.reduce((a,s)=>a+(G.std[s.id]?.wc||0),0),t=ss.reduce((a,s)=>a+(G.std[s.id]?.wt||0),0),cov=coverage(ss),r=readiness(ss);return {id:cat.id,title:cat.title,c,t,accuracy:t?Math.round(c/t*100):null,coverage:cov.pct,readiness:r,count:ss.length,evidence:cov.n}})}
function barRows(obj,order=[]){const keys=[...order.filter(k=>obj[k]?.[1]),...Object.keys(obj).filter(k=>!order.includes(k)&&obj[k]?.[1])];if(!keys.length)return '<p class="empty-state">No validated categorized assessment evidence yet.</p>';return `<div class="analytics-bars">${keys.map(k=>{const v=obj[k],p=pairPct(v);return `<div class="analytics-bar-row"><div><strong>${esc(k)}</strong><span>${v[1]} question${v[1]===1?'':'s'}</span></div><div class="analytics-meter"><i style="width:${p||0}%"></i></div><b>${p==null?'—':p+'%'}</b></div>`}).join('')}</div>`}
function domainCards(list){return `<div class="domain-analytics-grid">${list.map(d=>`<article class="domain-analytics-card"><div><span>${esc(d.id)}</span><strong>${esc(d.title)}</strong></div><div class="domain-score">${d.readiness}<small>/100 evidence index</small></div><div class="analytics-meter"><i style="width:${d.readiness}%"></i></div><p>${d.accuracy==null?'No validated question evidence yet':`${d.accuracy}% weighted evidence accuracy`} · ${d.evidence}/${d.count} standards tested</p></article>`).join('')}</div>`}
function reason(s,z){const reasons=[];if(z.due&&z.due<=Date.now())reasons.push('retention due');if(z.validPct<70)reasons.push(`${z.validPct}% validated accuracy`);else if(z.validPct<80)reasons.push('below mastery target');if(z.sessions<2)reasons.push('low session evidence');if((BANK[s.id]||0)<2)reasons.push('limited current bank breadth');if((z.streak||0)===0)reasons.push('latest retrieval incomplete');return reasons.slice(0,2).join(' · ')||'needs more evidence'}
function competencyList(mode){let list=[...D.cetaStandards,...D.careerStandards].filter(s=>s.assessable!==false&&G.std[s.id]?.wt).map(s=>({s,z:G.std[s.id],cf:confidence(G.std[s.id],s.id)}));if(mode==='weak')list.sort((a,b)=>(state(a.s.id)==='Retention Due'?-100:0)+a.cf-((state(b.s.id)==='Retention Due'?-100:0)+b.cf));else list=list.filter(x=>x.z.wt>=2).sort((a,b)=>b.cf-a.cf||b.z.validPct-a.z.validPct);return list.slice(0,12)}
function compHtml(list,weak){if(!list.length)return '<p class="empty-state">Take current optional assessments to build validated competency evidence.</p>';return `<div class="competency-rank-list">${list.map(({s,z,cf})=>`<article><div><span>${esc(s.track)} · ${esc(s.code)}</span><strong>${esc(s.categoryTitle)}</strong><p>${esc(s.text)}</p>${weak?`<a class="text-link" href="study.html?standard=${encodeURIComponent(s.id)}#review-queue">Review in Study →</a>`:''}</div><div class="competency-score ${weak&&cf<60?'danger':''}"><b>${cf}</b><small>confidence</small><span>${z.validPct}% weighted · ${z.t} Q</span>${weak?`<em>${esc(reason(s,z))}</em>`:`<em>${esc(state(s.id))}</em>`}</div></article>`).join('')}</div>`}
function renderTrend(){const list=G.trend.slice(-16);if(!list.length)return '<p class="empty-state">No assessment trend yet.</p>';return `<div class="trend-strip">${list.map(v=>`<div class="trend-item" title="${esc(v[2])} · ${v[1]}%"><div class="trend-column"><i style="height:${Math.max(4,v[1])}%"></i></div><strong>${v[1]}%</strong><small>${new Date(v[0]).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></div>`).join('')}</div>`}
function render(){
 const cetaReady=readiness(D.cetaStandards),careerReady=readiness(D.careerStandards),overall=Math.round((cetaReady+careerReady)/2),due=[...D.cetaStandards,...D.careerStandards].filter(s=>state(s.id)==='Retention Due').length,cetaCov=coverage(D.cetaStandards),careerCov=coverage(D.careerStandards),validated=Object.values(G.k).reduce((n,v)=>n+v[1],0),legacy=G.legacyQ[1]||0;
 $('#analytics-kpis').innerHTML=`<div><strong>${overall}</strong><span>overall evidence index /100</span></div><div><strong>${cetaReady}</strong><span>CETa evidence index /100</span></div><div><strong>${careerReady}</strong><span>career evidence index /100</span></div><div><strong>${due}</strong><span>retention due</span></div>`;
 $('#analytics-overview').innerHTML=`<article><span>Validated assessment evidence</span><strong>${validated.toLocaleString()}</strong><p>${validated?Math.round(Object.values(G.k).reduce((n,v)=>n+v[0],0)/validated*100)+'% validated accuracy':'No current-bank questions answered yet'}</p></article><article><span>Assessment attempts</span><strong>${G.attempts}</strong><p>${Math.round(G.sec/60).toLocaleString()} minutes recorded</p></article><article><span>CETa coverage</span><strong>${cetaCov.pct}%</strong><p>${cetaCov.n}/${cetaCov.total} assessable standards have validated evidence</p></article><article><span>Career coverage</span><strong>${careerCov.pct}%</strong><p>${careerCov.n}/${careerCov.total} standards have validated evidence</p></article><article><span>Lab evidence</span><strong>${G.labs.academic}/${G.labs.total}</strong><p>${G.labs.virtual} virtual · ${G.labs.physical} physical</p></article><article><span>Local progress payload</span><strong>${(G.localBytes/1024).toFixed(1)} KB</strong><p>Cloud records remain compact JSON</p></article>`;
 $('#ceta-domain-analytics').innerHTML=domainCards(domainStats('CETa'));$('#career-domain-analytics').innerHTML=domainCards(domainStats('Career'));$('#skill-analytics').innerHTML=barRows(G.k,['Recall','Understanding','Calculation','Analysis','Troubleshooting','Application']);$('#difficulty-analytics').innerHTML=barRows(G.d,['Foundation','Intermediate','Advanced']);$('#type-analytics').innerHTML=barRows(G.types,['Optional Week Practice','Lab Check','Weekly Review','Major Assessment']);$('#needs-attention').innerHTML=compHtml(competencyList('weak'),true);$('#strongest-competencies').innerHTML=compHtml(competencyList('strong'),false);$('#assessment-trend').innerHTML=renderTrend();
 $('#analytics-data-note').innerHTML=`<strong>Current evidence rule (revision ${esc(EVIDENCE_REVISION)}):</strong> ${validated.toLocaleString()} current-bank answers contribute skill/difficulty analytics. ${legacy.toLocaleString()} historical answers remain in score history. Earlier mixed-bank aggregates require revalidation and cannot establish current mastery. Automatic status uses current-bank accuracy, repeated sessions, retention, recency, and distinct bank breadth; a standard with fewer than two distinct reviewed items is Evidence Limited rather than falsely promoted. Indices summarize web evidence, not exam passage or hiring probability; low coverage may mean unmeasured knowledge. Repeated forms reuse questions. Physical competence requires physical evidence. Completed coursework is not reset.`;
}
render();window.addEventListener('alfred-progress-updated',()=>location.reload());
})();
