(()=>{
const D=window.ALFRED_ASSESSMENT||{}, A=window.ALFRED_ACADEMIC||{}, $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='alfred-u-progress-v2';
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return {}}}
function weekObj(v){return typeof v==='string'?{mastery:v,assessments:{},labs:{}}:{...(v||{}),mastery:v?.mastery||'',assessments:v?.assessments||{},labs:v?.labs||{}}}
function blank(){return {v:1,q:[0,0],sec:0,r:{},k:{},d:{},s:{},trend:[],firstAt:0,lastAt:0}}
function pairAdd(map,key,c,t){const x=map[key]||[0,0];x[0]+=Number(c||0);x[1]+=Number(t||0);map[key]=x}
function derived(a){if(a?.analytics?.v===1)return a.analytics;const x=blank();[...(a?.attempts||[])].sort((u,v)=>Date.parse(u.at||0)-Date.parse(v.at||0)).forEach(at=>{const ts=Date.parse(at.at||'')||0,c=Number(at.correct||0),t=Number(at.total||0);x.q[0]+=c;x.q[1]+=t;x.sec+=Number(at.seconds||0);if(ts){x.firstAt=x.firstAt||ts;x.lastAt=Math.max(x.lastAt,ts);x.trend.push([ts,Number(at.pct||0)])}(at.r||[]).forEach(v=>pairAdd(x.r,v[0],v[1],v[2]));(at.k||[]).forEach(v=>pairAdd(x.k,v[0],v[1],v[2]));(at.d||[]).forEach(v=>pairAdd(x.d,v[0],v[1],v[2]));(at.s||[]).forEach(row=>{const id=row[0],sc=Number(row[1]||0),st=Math.max(1,Number(row[2]||1)),z=x.s[id]||[0,0,0,0,0,0,0];z[0]+=sc;z[1]+=st;z[2]+=1;z[3]=sc;z[4]=st;z[5]=ts;z[6]=sc===st?z[6]+1:0;x.s[id]=z;});});return x}
function records(){const p=load(),out=[];Object.entries(p.events||{}).forEach(([id,e])=>{if(e?.assessments?.lesson)out.push({type:'Lesson Quiz',key:`lesson:${id}`,a:e.assessments.lesson})});Object.entries(p.weeks||{}).forEach(([week,raw])=>{const w=weekObj(raw);Object.entries(w.assessments||{}).forEach(([key,a])=>{const kind=key.split(':')[0],label=kind==='lab'?'Lab Check':kind==='week'?'Weekly Test':kind==='major'?'Major Assessment':'Assessment';out.push({type:label,key:`${week}:${key}`,a})})});return out}
function aggregate(){
 const p=load(),recs=records(),g={q:[0,0],sec:0,r:{},k:{},d:{},types:{},trend:[],std:{},recentStd:{},attempts:0,records:recs.length};
 recs.forEach(rec=>{const x=derived(rec.a);g.q[0]+=Number(x.q?.[0]||0);g.q[1]+=Number(x.q?.[1]||0);g.sec+=Number(x.sec||0);pairAdd(g.types,rec.type,x.q?.[0]||0,x.q?.[1]||0);Object.entries(x.r||{}).forEach(([k,v])=>pairAdd(g.r,k,v[0],v[1]));Object.entries(x.k||{}).forEach(([k,v])=>pairAdd(g.k,k,v[0],v[1]));Object.entries(x.d||{}).forEach(([k,v])=>pairAdd(g.d,k,v[0],v[1]));(x.trend||[]).forEach(v=>g.trend.push([Number(v[0]||0),Number(v[1]||0),rec.type]));g.attempts+=Number(rec.a?.attemptCount||(rec.a?.attempts||[]).length||0);
   Object.entries(x.s||{}).forEach(([sid,v])=>{const z=g.std[sid]||{c:0,t:0,sessions:0,last:0,lastC:0,lastT:0,history:[]};z.c+=Number(v[0]||0);z.t+=Number(v[1]||0);z.sessions+=Number(v[2]||0);const last=Number(v[5]||0);if(last>z.last){z.last=last;z.lastC=Number(v[3]||0);z.lastT=Number(v[4]||0)}g.std[sid]=z;});
   (rec.a?.attempts||[]).forEach(at=>{const ts=Date.parse(at.at||'')||0;(at.s||[]).forEach(row=>{const sid=row[0],z=g.std[sid]||{c:0,t:0,sessions:0,last:0,lastC:0,lastT:0,history:[]};z.history.push({at:ts,c:Number(row[1]||0),t:Math.max(1,Number(row[2]||1))});g.std[sid]=z;});});
 });
 Object.values(g.std).forEach(z=>{z.history.sort((a,b)=>a.at-b.at);let streak=0;for(let i=z.history.length-1;i>=0;i--){if(z.history[i].c===z.history[i].t)streak++;else break}z.streak=streak;if(z.history.length){const h=z.history[z.history.length-1];z.last=h.at;z.lastC=h.c;z.lastT=h.t}z.pct=z.t?Math.round(z.c/z.t*100):0;const ok=z.lastT>0&&z.lastC===z.lastT,days=ok?(streak>=3?45:streak===2?21:7):2;z.due=z.last?z.last+days*86400000:0;});
 g.trend.sort((a,b)=>a[0]-b[0]);
 let virtual=0,physical=0,academic=0;Object.values(p.weeks||{}).forEach(raw=>{const w=weekObj(raw);Object.values(w.labs||{}).forEach(l=>{if(l.virtual)virtual++;if(l.physical)physical++;if(l.virtual||l.physical)academic++;});});g.labs={virtual,physical,academic,total:(A.labs||[]).length||24};
 g.localBytes=new Blob([JSON.stringify(p)]).size;return g;
}
const G=aggregate(),stdIndex=new Map([...D.cetaStandards,...D.careerStandards].map(s=>[s.id,s]));
function confidence(z){if(!z||!z.t)return 0;const acc=z.c/z.t,evid=Math.min(1,z.t/12)*.65+Math.min(1,z.sessions/4)*.35,age=z.last?Math.max(0,(Date.now()-z.last)/86400000):999,rec=age<=7?1:age<=21?.9:age<=45?.75:age<=90?.55:.35,cons=Math.min(1,(z.streak||0)/3);return Math.round(100*(acc*.55+evid*.20+rec*.10+cons*.15))}
function state(id){const z=G.std[id];if(!z)return 'Not Introduced';if(z.due&&z.due<=Date.now())return 'Retention Due';const cf=confidence(z);if(z.t<3||z.sessions<2)return 'Learning';if(cf>=85&&z.pct>=85&&z.streak>=3&&z.sessions>=3)return 'Mastered';if(cf>=72&&z.pct>=80&&z.sessions>=2)return 'Proficient';return 'Developing'}
function pairPct(v){return v&&v[1]?Math.round(v[0]/v[1]*100):null}
function readiness(list){if(!list.length)return 0;return Math.round(list.reduce((sum,s)=>sum+confidence(G.std[s.id]),0)/list.length)}
function coverage(list){const n=list.filter(s=>G.std[s.id]?.t).length;return {n,total:list.length,pct:list.length?Math.round(n/list.length*100):0}}
function domainStats(track){const standards=track==='CETa'?D.cetaStandards:D.careerStandards,cats=track==='CETa'?D.cetaCategories:D.careerDomains;return cats.map(cat=>{const ss=standards.filter(s=>s.category===cat.id),c=ss.reduce((a,s)=>a+(G.std[s.id]?.c||0),0),t=ss.reduce((a,s)=>a+(G.std[s.id]?.t||0),0),cov=coverage(ss),r=readiness(ss);return {id:cat.id,title:cat.title,c,t,accuracy:t?Math.round(c/t*100):null,coverage:cov.pct,readiness:r,count:ss.length,evidence:cov.n}})}
function barRows(obj,order=[]){const keys=[...order.filter(k=>obj[k]),...Object.keys(obj).filter(k=>!order.includes(k))];if(!keys.length)return '<p class="empty-state">No categorized assessment evidence yet.</p>';return `<div class="analytics-bars">${keys.map(k=>{const v=obj[k],p=pairPct(v);return `<div class="analytics-bar-row"><div><strong>${esc(k)}</strong><span>${v[1]} question${v[1]===1?'':'s'}</span></div><div class="analytics-meter"><i style="width:${p||0}%"></i></div><b>${p==null?'—':p+'%'}</b></div>`}).join('')}</div>`}
function domainCards(list){return `<div class="domain-analytics-grid">${list.map(d=>`<article class="domain-analytics-card"><div><span>${esc(d.id)}</span><strong>${esc(d.title)}</strong></div><div class="domain-score">${d.readiness}<small>/100 readiness</small></div><div class="analytics-meter"><i style="width:${d.readiness}%"></i></div><p>${d.accuracy==null?'No question evidence yet':`${d.accuracy}% evidence accuracy`} · ${d.evidence}/${d.count} standards tested</p></article>`).join('')}</div>`}
function reason(s,z){const reasons=[];if(z.due&&z.due<=Date.now())reasons.push('retention due');if(z.pct<70)reasons.push(`${z.pct}% accuracy`);else if(z.pct<80)reasons.push('below mastery target');if(z.sessions<2)reasons.push('low evidence');if((z.streak||0)===0)reasons.push('latest retrieval incomplete');return reasons.slice(0,2).join(' · ')||'needs more evidence'}
function competencyList(mode){let list=[...D.cetaStandards,...D.careerStandards].filter(s=>G.std[s.id]?.t).map(s=>({s,z:G.std[s.id],cf:confidence(G.std[s.id])}));if(mode==='weak')list.sort((a,b)=>(state(a.s.id)==='Retention Due'?-100:0)+a.cf-((state(b.s.id)==='Retention Due'?-100:0)+b.cf));else list=list.filter(x=>x.z.t>=3).sort((a,b)=>b.cf-a.cf||b.z.pct-a.z.pct);return list.slice(0,12)}
function compHtml(list,weak){if(!list.length)return '<p class="empty-state">Take assessments to build competency evidence.</p>';return `<div class="competency-rank-list">${list.map(({s,z,cf})=>`<article><div><span>${esc(s.track)} · ${esc(s.code)}</span><strong>${esc(s.categoryTitle)}</strong><p>${esc(s.text)}</p></div><div class="competency-score ${weak&&cf<60?'danger':''}"><b>${cf}</b><small>confidence</small><span>${z.pct}% · ${z.t} Q</span>${weak?`<em>${esc(reason(s,z))}</em>`:`<em>${esc(state(s.id))}</em>`}</div></article>`).join('')}</div>`}
function renderTrend(){const list=G.trend.slice(-16);if(!list.length)return '<p class="empty-state">No assessment trend yet.</p>';return `<div class="trend-strip">${list.map(v=>`<div class="trend-item" title="${esc(v[2])} · ${v[1]}%"><div class="trend-column"><i style="height:${Math.max(4,v[1])}%"></i></div><strong>${v[1]}%</strong><small>${new Date(v[0]).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></div>`).join('')}</div>`}
function render(){
 const cetaReady=readiness(D.cetaStandards),careerReady=readiness(D.careerStandards),overall=Math.round((cetaReady+careerReady)/2),due=[...D.cetaStandards,...D.careerStandards].filter(s=>state(s.id)==='Retention Due').length,cetaCov=coverage(D.cetaStandards),careerCov=coverage(D.careerStandards),categorized=Object.values(G.k).reduce((n,v)=>n+v[1],0);
 $('#analytics-kpis').innerHTML=`<div><strong>${overall}</strong><span>overall confidence /100</span></div><div><strong>${cetaReady}</strong><span>CETa readiness /100</span></div><div><strong>${careerReady}</strong><span>career readiness /100</span></div><div><strong>${due}</strong><span>retention due</span></div>`;
 $('#analytics-overview').innerHTML=`<article><span>Assessment evidence</span><strong>${G.q[1].toLocaleString()}</strong><p>${G.q[1]?Math.round(G.q[0]/G.q[1]*100)+'% lifetime accuracy':'No questions answered yet'}</p></article><article><span>Assessment attempts</span><strong>${G.attempts}</strong><p>${Math.round(G.sec/60).toLocaleString()} minutes recorded</p></article><article><span>CETa coverage</span><strong>${cetaCov.pct}%</strong><p>${cetaCov.n}/${cetaCov.total} standards have evidence</p></article><article><span>Career coverage</span><strong>${careerCov.pct}%</strong><p>${careerCov.n}/${careerCov.total} standards have evidence</p></article><article><span>Lab evidence</span><strong>${G.labs.academic}/${G.labs.total}</strong><p>${G.labs.virtual} virtual · ${G.labs.physical} physical</p></article><article><span>Local progress payload</span><strong>${(G.localBytes/1024).toFixed(1)} KB</strong><p>Cloud records remain compact JSON</p></article>`;
 $('#ceta-domain-analytics').innerHTML=domainCards(domainStats('CETa'));$('#career-domain-analytics').innerHTML=domainCards(domainStats('Career'));
 $('#skill-analytics').innerHTML=barRows(G.k,['Recall','Understanding','Calculation','Analysis','Troubleshooting','Application']);$('#difficulty-analytics').innerHTML=barRows(G.d,['Foundation','Application','Calculation']);$('#type-analytics').innerHTML=barRows(G.types,['Lesson Quiz','Lab Check','Weekly Test','Major Assessment']);
 $('#needs-attention').innerHTML=compHtml(competencyList('weak'),true);$('#strongest-competencies').innerHTML=compHtml(competencyList('strong'),false);$('#assessment-trend').innerHTML=renderTrend();
 const legacy=Math.max(0,G.q[1]-categorized);$('#analytics-data-note').innerHTML=`<strong>Analytics coverage:</strong> ${categorized.toLocaleString()} question${categorized===1?'':'s'} include skill/difficulty analytics.${legacy?` ${legacy.toLocaleString()} older question${legacy===1?'':'s'} are preserved in standards/score history but do not have retrospective cognitive tags.`:''} Lifetime standard totals remain after detailed attempts roll off the three-attempt review window.`;
}
render();
window.addEventListener('alfred-progress-updated',()=>location.reload());
})();
