const fs=require('fs'),vm=require('vm'),assert=require('assert');
const els=new Map(),store=new Map();function el(id){if(!els.has(id))els.set(id,{value:'',innerHTML:'',textContent:'',style:{},classList:{add(){},remove(){},contains(){return false}},setAttribute(){},addEventListener(){},scrollIntoView(){},insertAdjacentHTML(_,s){this.innerHTML+=s}});return els.get(id)}
const ctx={window:{},document:{querySelector:el,querySelectorAll:()=>[],body:el('body')},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},location:{search:'?event=2'},URLSearchParams,Intl,Date,console,navigator:{onLine:false}};
vm.createContext(ctx);for(const f of ['course-data.js','academic-content.js'])vm.runInContext(fs.readFileSync('alfred-university/'+f,'utf8'),ctx);
let src=fs.readFileSync('alfred-university/study.js','utf8');src=src.slice(0,src.indexOf('enqueueRequestedStandard();hydrateReviewsFromProgress();'))+`window.test={buildSteps,modePlan,renderSession,renderResumeSession,finishSession,renderReviews,renderCompetencyReviews,setStep:n=>step=n,setBlock:n=>reviewedThisBlock=n,setTarget:e=>target=e,getState:()=>state};})();`;vm.runInContext(src,ctx);
const t=ctx.window.test,e=ctx.window.ALFRED_EVENTS[1];
for(const [mode,total] of [['quick',20],['standard',60],['deep',120]]){assert.equal(t.modePlan(mode,e).reduce((n,x)=>n+x.minutes,0),total);const steps=t.buildSteps(e,mode);assert(steps[1].body.includes('Assigned work'));assert(steps[1].body.includes('Book assignment:'));}
t.setStep(1);t.renderSession();el('#session-note').value='Recheck R2 < safely';el('#session-note').oninput();assert.equal(JSON.parse(store.get('alfred-u-study-v13')).session.note,'Recheck R2 < safely');t.finishSession();assert.equal(t.getState().session.step,1);assert(!store.has('alfred-u-progress-v2'));t.renderResumeSession();assert(el('#resume-session-copy').textContent.includes('Recheck R2'));el('#resume-session-button').onclick();assert.equal(t.getState().session.step,1);
t.setBlock(3);t.renderReviews();assert(el('#review-queue').innerHTML.includes('Review block complete'));assert(!el('#review-queue').innerHTML.includes('data-review-id'));el('#more-reviews').onclick();
const html=fs.readFileSync('alfred-university/study.html','utf8');assert(html.indexOf('id="resume-session-section"')<html.indexOf('id="start-session-section"'));
console.log('PASS: mode totals; assigned task/book reading; note persistence; pause/resume; no accidental completion; review stopping point; resume placement. Node VM behavior tests, not browser rendering.');
