/* v16.3: bounded preparation guidance and explicit readiness evidence rules. */
(()=>{'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const host=document.getElementById('readiness-guide');
if(host){host.innerHTML=`<h2>Your two finish lines</h2><p>Use the existing assignments to prepare for CETa and build evidence for technician applications. These checks clarify the work; they do not add another course or gradebook.</p>
<details><summary>CETa: understand, calculate and explain</summary><p>Complete every required Classroom lesson check, assigned lab check, and weekly mastery gate. Use the assigned booklet reading, chapter questions, current ETA competencies, and sixth-edition errata as reinforcement; none of those external resources substitutes for Alfred’s in-house teaching path.</p><p>Before booking the official exam, complete <strong>one current full-length 100-question Alfred CETa practice run at 85% or higher</strong> and <strong>one separate current independent CETa practice assessment at 85% or higher from outside the Alfred question bank</strong>. Review every error between the two checks, then explain the reasoning without recognizing an answer from memory. Repeating the Alfred mock is still useful retrieval practice, but because its reviewed bank necessarily reuses material, a repeat Alfred run does not count as the independent second gate. Also work through the booklet’s practice exams on separate occasions and use fresh calculations, diagrams, and waveforms to verify weak topics.</p><p>ETA lists 100 questions, two hours and a 75% passing score. That 75% is the official exam standard. Alfred’s dual-source 85% rule is a conservative internal readiness gate; it is not an official ETA requirement, prediction, or guarantee. The five-per-domain Alfred form is a breadth design, not published ETA weighting. Confirm current arrangements, permitted formula references, and accommodations with the test administrator.</p><p><a href="https://www.etai.org/electronics.html">ETA exam information</a> · <a href="https://www.etai.org/comps/CETa_comps.pdf">Current competencies</a> · <a href="https://www.etai.org/6thEdASTErrataSheet.pdf">Sixth-edition errata</a> · <a href="assessments.html#coverage-map">Alfred coverage map</a></p><p>Apply the errata before learning the affected resonance, reactance, amplifier, logic, and inductance answers. For physical work, follow equipment ratings and manufacturer instructions. Keep course experiments at safe, isolated low voltage; a printed example involving mains is not a direction to reproduce it.</p></details>
<details><summary>Technician applications: show what you can do</summary><p>Reuse your scheduled labs and projects to demonstrate these skills. Describe simulated and physical work accurately.</p><ul><li><strong>Measure safely:</strong> read a schematic; use a DMM, current-limited supply and oscilloscope; explain settings, expected values, tolerances and instrument limitations.</li><li><strong>Find a fault:</strong> record the symptom, isolate a section, test a hypothesis, repair or explain the cause, and retest. Separate fixture faults from board faults.</li><li><strong>Bring up firmware:</strong> build and flash your STM32 project, debug with SWD, read a sensor over a serial bus and explain timing and error handling.</li><li><strong>Automate a test:</strong> use Python to collect real device data, enforce a timeout, exercise normal and failure conditions, and retain clear pass/fail results with revisions and setup details.</li><li><strong>Communicate the evidence:</strong> show one coherent project repository and test report. Explain your own decisions, limitations and next diagnostic step. Demonstrate soldering or harness work when the target role requires it.</li></ul><p>Simulation keeps learning moving, and software tests provide real software evidence. Neither proves probe handling, solder quality or physical board debugging. Access to a school lab, makerspace or supervised bench can supply those missing repetitions without buying every instrument.</p><p>Target electronics technician, hardware test technician, engineering technician and relevant production-test roles whose duties include schematics, measurements, troubleshooting or test automation. A title alone does not establish useful bridge experience. Check required experience, schedule and education against each posting. Week 30 remains the planned application push; apply earlier when you can demonstrate the stated entry requirements.</p><p>This is a foundation for a paid bridge role while you continue school. Embedded engineering also requires deeper design, mathematics, software architecture and employer-specific experience. Technician work can strengthen that path; it does not automatically replace degree or experience requirements. Learn specialized RF, environmental-test or production equipment when a real role calls for it.</p></details>`;
if(location.pathname.endsWith('week.html')){const w=Number(new URLSearchParams(location.search).get('week'));if(w<21)host.querySelectorAll('details').forEach(d=>d.open=false);}
}
const coverage=document.getElementById('audit-coverage'),data=window.ALFRED_ASSESSMENT;
if(coverage&&data){const rows=data.meta.coverage||[];coverage.innerHTML=rows.map(r=>`<details><summary>${esc(r.id)}. ${esc(r.title)} — ${r.practiceItems} active reviewed bank items</summary><p><strong>Assigned book:</strong> ${esc(r.book)}. <strong>Course weeks:</strong> ${r.weeks.join(', ')}.</p><p>${r.directlySampled} of ${r.objectiveRows} listed objective rows have a directly tagged active reviewed Alfred bank question. <strong>${r.semanticRows||0} of ${r.objectiveRows}</strong> have a required v16.3 subject-specific semantic task. These are different evidence types; neither is ETA exam weighting.</p><p><strong>Rows without a direct active bank question:</strong> ${r.notDirectlySampled.length?r.notDirectlySampled.map(esc).join(', '):'None.'} These rows are still assessed through their required topic-specific semantic task, weekly mastery, and any applicable lab/application evidence.</p></details>`).join('');}
})();
