(()=>{
const A=window.ALFRED_ACADEMIC||{},D=window.ALFRED_ASSESSMENT||{},C=window.ALFRED_CURRICULUM||{},W=window.ALFRED_WEEKS||[],E=window.ALFRED_EVENTS||[],R0=window.ALFRED_RESOURCES||[],REL=window.ALFRED_RELEASES||[];
const $=(s,r=document)=>r.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=s=>String(s??'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9+.#/\- ]/g,' ').replace(/\s+/g,' ').trim();
const terms=q=>norm(q).split(' ').filter(Boolean);
const items=[];
add('Site Tool','Competency Dashboard','Learning analytics dashboard for CETa readiness, career readiness, standards confidence, retention due, cognitive skill performance, difficulty performance, assessment trends, and lab evidence.','analytics.html',{source:'Alfred learning analytics'},5);
function add(type,title,text,url,meta={},boost=1){items.push({type,title,text:String(text||''),url,meta,boost,hay:norm([title,text,JSON.stringify(meta)].join(' '))});}
A.cetaDomains.forEach(d=>add('CETa Domain',`${d.id}.0 ${d.title}`,`${d.summary} ${d.keywords}`,'assessments.html#domain-'+d.id,{domain:d.id,weeks:d.weeks},5));
(C.modules||[]).forEach(m=>{
  (m.lessons||[]).forEach((lesson,index)=>add('Classroom Lesson',`Week ${String(m.week).padStart(2,'0')} · ${lesson.title}`,[m.promise,...(lesson.objectives||[]),...(lesson.integrated?.teaching||[]).flatMap(section=>[section.title,section.text,section.remember]),lesson.integrated?.purpose,lesson.integrated?.prereq,...(lesson.integrated?.guidedPractice||[]),lesson.integrated?.independentScenario,lesson.integrated?.connection,lesson.integrated?.teachBack,...(lesson.integrated?.semanticTasks||[]).flatMap(section=>[section.title,section.prompt,...(section.required||[])]),...(lesson.integrated?.workedExamples||[]).flatMap(x=>[x.problem,...(x.steps||[]),x.answer,x.meaning,x.transfer]),...(m.commonMistakes||[])].join(' '),`learn.html?week=${m.week}&stage=${index===0?'ceta-lesson':'career-lesson'}`,{week:m.week,domain:m.standards?.ceta,track:lesson.track,source:'Alfred Classroom'},7));
  add('Classroom Lesson',`Week ${String(m.week).padStart(2,'0')} · ${m.integration.title}`,[m.integration.brief,...(m.integration.guided||[]),m.integration.independent,m.integration.evidence,m.integration.practiceCheck].join(' '),`learn.html?week=${m.week}&stage=practice`,{week:m.week,domain:m.standards?.ceta,track:'CETa + Career',source:'Alfred Classroom'},6);
});
W.forEach(w=>add('Week Module',`Week ${String(w.week).padStart(2,'0')} · ${w.topic}`,(w.outcomes||[]).join(' '),'week.html?week='+w.week,{week:w.week},4));
E.forEach(e=>add('Scheduled Session',e.summary,`${e.today||''} ${e.description||''} ${(e.outcomes||[]).join(' ')}`,'calendar.html?event='+e.id,{week:e.week,type:e.type},2));
A.labs.forEach(l=>add('Lab',`${l.id} · ${l.title}`,`${l.objective} ${l.equipment} ${(l.procedure||[]).join(' ')} ${l.evidence} ${l.career}`,'labs.html?week='+l.week+'#'+encodeURIComponent(l.id),{week:l.week,domain:l.ceta},4));
A.knowledge.forEach(k=>add('Knowledge',k.term,`${k.summary} ${k.deeper} ${k.formula} ${k.keywords}`,'knowledge.html?domain='+k.domain+'&q='+encodeURIComponent(k.term),{week:k.weeks,domain:[k.domain]},4));
A.deepResources.forEach(r=>add('Resource',r.title,`${r.summary} ${r.keywords} ${r.source} ${r.kind} ${r.career}`,r.url,{week:r.weeks,domain:r.ceta,source:r.source,kind:r.kind,external:true},r.priority==='CETa CORE'?6:3));
R0.forEach(r=>add('Resource',r.title,`${r.category||''} ${r.domain||''} ${(r.contexts||[]).join(' ')}`,r.url,{week:r.weeks,source:r.domain,external:true},2));
A.localDocuments.forEach(d=>{const historical=/Academic System Guide/i.test(d.title||'')||/historical|superseded/i.test(d.source||'');add('Document',d.title,d.text,d.url,{source:d.source,fulltext:true,historical},historical?0.75:3)});
REL.forEach(r=>add('Release Note',`${r.version} · ${r.title}`,`${r.request} ${(r.changes||[]).join(' ')} ${r.type} ${r.date}`,'patch-notes.html#release-'+r.version.replace(/[^a-z0-9]+/gi,'-'),{source:'Alfred University release history'},2));
;(D.cetaStandards||[]).forEach(s=>add('CETa Standard',`CETa ${s.code} · ${s.categoryTitle}`,`${s.text} ${s.sourceChapter||''}`,'standards.html?standard='+encodeURIComponent(s.id),{domain:s.category,source:'ETA competency framework'},6));
;(D.careerStandards||[]).forEach(s=>add('Career Standard',`${s.code} · ${s.categoryTitle}`,s.text,'standards.html?standard='+encodeURIComponent(s.id),{source:'Alfred career transition standards'},5));
;(D.majorAssessments||[]).forEach(a=>add('Assessment',a.title,a.description,'quiz.html?type=major&id='+a.id,{source:'Assessment Center'},3));
const input=$('#global-search-input'), form=$('#global-search-form'), typeSel=$('#search-type'), domainSel=$('#search-domain'), out=$('#search-results'), summary=$('#search-summary');
A.cetaDomains.forEach(d=>domainSel.insertAdjacentHTML('beforeend',`<option value="${d.id}">${d.id}.0 ${esc(d.title)}</option>`));
$('#search-scope-note').textContent=A.meta.searchNote;
function snippet(text,toks){let clean=String(text||'').replace(/\s+/g,' ').trim(); if(!clean)return ''; const lower=clean.toLowerCase(); let pos=-1; for(const t of toks){const p=lower.indexOf(t);if(p>=0&&(pos<0||p<pos))pos=p;} if(pos<0)pos=0; const start=Math.max(0,pos-130), end=Math.min(clean.length,start+420); return (start?'…':'')+clean.slice(start,end)+(end<clean.length?'…':'');}
function score(it,toks){let s=0; const title=norm(it.title); toks.forEach(t=>{if(title===t)s+=30;else if(title.includes(t))s+=12; const m=it.hay.split(t).length-1;s+=Math.min(m,8)*2;}); return s*it.boost;}
function render(){const q=input.value.trim(), toks=terms(q), type=typeSel.value, domain=domainSel.value; let list=items.filter(it=>(!type||it.type===type)&&(!domain||(Array.isArray(it.meta.domain)?it.meta.domain.map(String).includes(domain):String(it.meta.domain||'')===domain))); if(toks.length)list=list.map(it=>({...it,_score:score(it,toks)})).filter(it=>it._score>0).sort((a,b)=>b._score-a._score); else list=list.map(it=>({...it,_score:0})); const total=list.length,limit=toks.length?120:80,visible=list.slice(0,limit);summary.innerHTML=`Showing <strong>${visible.length}</strong> of <strong>${total}</strong> result${total===1?'':'s'}${q?` for “${esc(q)}”`:''}${total>visible.length?' · Narrow your search or filters to see more specific results.':''}`; out.innerHTML=visible.map(it=>`<article class="search-result"><div class="search-result-meta"><span>${esc(it.type)}</span>${it.meta.fulltext?'<span>Full-text indexed PDF</span>':''}${it.meta.localPdf?'<span>Stored locally</span>':''}${it.meta.external?'<span>External publisher</span>':''}</div><h2>${esc(it.title)}</h2>${it.meta.historical?'<p class="filter-guidance"><strong>Historical document — not current operating instructions.</strong> Use the live Classroom, current Assessment Center, Progress, and Deployment pages for current workflow.</p>':''}<p>${esc(snippet(it.text,toks))}</p><div class="search-result-foot"><div><a href="${esc(it.url)}" ${(it.meta.external||it.meta.localPdf)?'target="_blank" rel="noopener"':''}>Open ${it.type.toLowerCase()} ${(it.meta.external)?'↗':'→'}</a>${it.meta.publisherUrl?`<a class="search-source-link" href="${esc(it.meta.publisherUrl)}" target="_blank" rel="noopener">Source ↗</a>`:''}</div>${it.meta.week?`<span>${(Array.isArray(it.meta.week)?it.meta.week:[it.meta.week]).filter(Boolean).slice(0,8).map(w=>'W'+w).join(' · ')}</span>`:''}</div></article>`).join('')||'<p class="empty-state">No content matched. Try a broader concept or search by CETa domain.</p>';}
form.addEventListener('submit',e=>{e.preventDefault(); const u=new URL(location.href); if(input.value)u.searchParams.set('q',input.value);else u.searchParams.delete('q'); history.replaceState(null,'',u);render();}); [typeSel,domainSel].forEach(x=>x.addEventListener('change',render)); input.addEventListener('input',()=>{clearTimeout(input._t);input._t=setTimeout(render,120)}); const q0=new URLSearchParams(location.search).get('q');if(q0)input.value=q0;render();
})();
