(()=>{
const D=window.ALFRED_ASSESSMENT||{}, $=(s,r=document)=>r.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const EVIDENCE_REVISION=String(D.meta?.evidenceRevision||D.meta?.version||'16.2');
const KEY='alfred-u-progress-v2';
// Automatic mastery breadth is intentionally based only on independently scored bank items.
// Semantic tasks remain separate rubric/self-reviewed evidence and do not inflate this count.
const BANK={};(D.questions||[]).filter(q=>q?.masteryEvidence!==false&&q?.difficulty!=='Orientation'&&!q?.retired).forEach(q=>(q.standards||[]).forEach(id=>BANK[id]=(BANK[id]||0)+1));
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return {}}}
function weekObj(v){return typeof v==='string'?{mastery:v,assessments:{}}:{mastery:v?.mastery||'',assessments:v?.assessments||{}}}
function allAssessmentRecords(p){const out=[];Object.values(p.events||{}).forEach(e=>{if(e?.assessments?.lesson)out.push(e.assessments.lesson)});Object.values(p.weeks||{}).forEach(raw=>{const w=weekObj(raw);Object.values(w.assessments||{}).forEach(a=>out.push(a))});return out}
function row(m,id){return m[id]??={id,total:0,correct:0,weightedTotal:0,weightedCorrect:0,high:0,sessions:0,last:0,lastCorrect:0,lastTotal:0,streak:0,legacyTotal:0}}
function evidence(){
 const p=load(),m={};
 // Current reviewed-bank lifetime evidence lives once in small category/domain shards.
 Object.values(p.analytics||{}).forEach(sh=>{
   Object.entries(sh?.legacyS||{}).forEach(([id,v])=>row(m,id).legacyTotal+=Number(v[1]||0));
   if(String(sh?.bankRevision||'')!==EVIDENCE_REVISION){Object.entries(sh?.s||{}).forEach(([id,v])=>row(m,id).legacyTotal+=Number(v[1]||0));Object.entries(sh?.l||{}).forEach(([id,n])=>row(m,id).legacyTotal+=Number(n||0));return;}
   Object.entries(sh?.s||{}).forEach(([id,v])=>{const z=row(m,id),c=Number(v[0]||0),t=Number(v[1]||0),sessions=Number(v[2]||0),lastC=Number(v[3]||0),lastT=Number(v[4]||0),lastAt=Number(v[5]||0),streak=Number(v[6]||0),wc=Number(v[7]||0),wt=Number(v[8]||0),high=Number(v[9]||0);z.correct+=c;z.total+=t;z.sessions+=sessions;z.weightedCorrect+=wc;z.weightedTotal+=wt;z.high+=high;if(lastAt>=z.last){z.last=lastAt;z.lastCorrect=lastC;z.lastTotal=lastT;z.streak=streak}});
   Object.entries(sh?.l||{}).forEach(([id,n])=>{row(m,id).legacyTotal+=Number(n||0)});
 });
 // Unmigrated v14.0/v14.1 records remain visible as legacy/revalidation evidence.
 allAssessmentRecords(p).forEach(a=>{const x=a?.analytics;if(String(x?.bankRevision||'')!==EVIDENCE_REVISION&&x?.s)Object.entries(x.s).forEach(([id,v])=>{row(m,id).legacyTotal+=Number(v[1]||0)});else if(x?.v===2&&x.s)Object.entries(x.s).forEach(([id,v])=>{const z=row(m,id),wt=Number(v[8]||0);if(wt){z.correct+=Number(v[0]||0);z.total+=Number(v[1]||0);z.sessions+=Number(v[2]||0);z.weightedCorrect+=Number(v[7]||0);z.weightedTotal+=wt;z.high+=Number(v[9]||0);const last=Number(v[5]||0);if(last>=z.last){z.last=last;z.lastCorrect=Number(v[3]||0);z.lastTotal=Number(v[4]||0);z.streak=Number(v[6]||0)}}else z.legacyTotal+=Number(v[1]||0)});else if(!x)(a?.attempts||[]).forEach(at=>Array.isArray(at?.s)&&at.s.forEach(v=>{const id=v?.[0],n=Number(v?.[2]||0);if(id&&n)row(m,id).legacyTotal+=n}))});
 Object.values(m).forEach(x=>{x.pct=x.total?Math.round(x.correct/x.total*100):0;x.validPct=x.weightedTotal?Math.round(x.weightedCorrect/x.weightedTotal*100):0;const ok=x.last&&x.lastCorrect===x.lastTotal,days=ok?(x.streak>=3?45:x.streak===2?21:7):2;x.due=x.last?new Date(x.last+days*86400000):null});
 return m;
}
const ev=evidence();
function confidence(x,id){if(!x||!x.weightedTotal)return 0;const accuracy=x.weightedCorrect/x.weightedTotal,evidence=Math.min(1,x.weightedTotal/8)*.60+Math.min(1,x.sessions/3)*.40,age=x.last?Math.max(0,(Date.now()-x.last)/86400000):999,recency=age<=7?1:age<=21?.9:age<=45?.75:age<=90?.55:.35,consistency=Math.min(1,(x.streak||0)/3),breadth=Math.min(1,(BANK[id]||0)/2),raw=Math.round(100*(accuracy*.50+evidence*.20+recency*.10+consistency*.10+breadth*.10));return raw}
function status(s){if(s.assessable===false)return 'Reference';const x=ev[s.id];if(!x||!x.weightedTotal)return x?.legacyTotal?'Revalidation Needed':'Not Introduced';if(x.due&&x.due<=new Date())return 'Retention Due';const cf=confidence(x,s.id);if(x.weightedTotal<2||x.sessions<2)return 'Learning';if((BANK[s.id]||0)<2)return 'Evidence Limited';if(cf>=85&&x.validPct>=85&&x.streak>=3&&x.sessions>=3)return 'Mastered';if(cf>=72&&x.validPct>=80&&x.sessions>=2)return 'Proficient';return 'Developing'}
function cls(x){return x==='Evidence Limited'?'learning':x.toLowerCase().replace(/\s+/g,'-')}
function renderSummary(){const all=[...D.cetaStandards,...D.careerStandards],counts={};all.forEach(s=>counts[status(s)]=(counts[status(s)]||0)+1);$('#standards-kpis').innerHTML=`<div><strong>${D.cetaStandards.length}</strong><span>CETa competency rows</span></div><div><strong>${D.careerStandards.length}</strong><span>career standards</span></div><div><strong>${counts.Mastered||0}</strong><span>mastered</span></div><div><strong>${counts['Retention Due']||0}</strong><span>retention due</span></div>`}
function render(){const track=$('#standard-track').value,cat=$('#standard-category').value,st=$('#standard-status').value,q=$('#standard-search').value.toLowerCase().trim(),base=track==='CETa'?D.cetaStandards:track==='Career'?D.careerStandards:[...D.cetaStandards,...D.careerStandards];const list=base.filter(s=>(!cat||s.category===cat)&&(!st||status(s)===st)&&(!q||`${s.id} ${s.code} ${s.text} ${s.categoryTitle}`.toLowerCase().includes(q)));$('#standard-count').textContent=`${list.length} standards shown`;$('#standard-list').innerHTML=list.map(s=>{const x=ev[s.id],z=status(s),cf=confidence(x,s.id);let evidenceHtml='<span>No validated assessment evidence yet</span>';if(s.assessable===false)evidenceHtml=`<span>${esc(s.note||'Reference row')}</span>`;else if(x?.weightedTotal)evidenceHtml=`<span>${x.correct}/${x.total} raw correct · ${x.pct}%</span><span>${x.sessions} validated session${x.sessions===1?'':'s'}</span><span>Validated accuracy ${x.validPct}%</span><span>Current reviewed bank breadth: ${BANK[s.id]||0} distinct item${(BANK[s.id]||0)===1?'':'s'}</span><span>Confidence ${cf}/100</span>${(BANK[s.id]||0)<2?'<span>Evidence Limited: automatic Mastered status requires at least two distinct current reviewed items</span>':''}${x.last?`<span>Last ${new Date(x.last).toLocaleDateString()}</span><span>Next retrieval ${x.due.toLocaleDateString()}</span>`:''}`;else if(x?.legacyTotal)evidenceHtml=`<span>${x.legacyTotal} legacy question${x.legacyTotal===1?'':'s'} retained for score history</span><span>Fresh current-bank practice builds current evidence; historical scores remain</span>`;return `<article class="standard-row"><div class="standard-code"><span>${esc(s.track)}</span><strong>${esc(s.code)}</strong></div><div class="standard-body"><div class="standard-title-row"><h3>${esc(s.categoryTitle)}</h3><span class="mastery-pill ${cls(z)}">${esc(z)}</span></div><p>${esc(s.text)}</p>${s.provenance?.sourceBasisText?`<div class="semantic-standard-route"><strong>Source basis:</strong> ${esc(s.provenance.relationship)} · ${esc(s.provenance.sourceBasisText)} · <a href="AU-ESET-301-v16.3.39-External-Source-Benchmark-Ledger.md" target="_blank" rel="noopener">Open source ledger ↗</a></div>`:''}${s.semanticTeaching?`<div class="semantic-standard-route"><strong>v16.3 integrated subject-specific route:</strong> Week ${esc(s.semanticTeaching.week)} · ${esc(s.semanticTeaching.section)} · ${esc(s.semanticTeaching.taskId)}</div>`:''}<div class="standard-evidence"><span>${esc(s.reconstructionStatus?`${s.reconstructionStatus} · source-traceable Career standard`:s.sourceChapter||'')}</span>${evidenceHtml}</div></div></article>`}).join('')||'<p class="empty-state">No standards match.</p>'}
function fillCats(){const sel=$('#standard-category');D.cetaCategories.forEach(c=>sel.insertAdjacentHTML('beforeend',`<option value="${c.id}" data-track="CETa">CETa ${c.id}.0 · ${esc(c.title)}</option>`));D.careerDomains.forEach(c=>sel.insertAdjacentHTML('beforeend',`<option value="${c.id}" data-track="Career">Career ${c.id} · ${esc(c.title)}</option>`))}
function renderCetaOutline(){const host=$('#ceta-outline-grid');if(!host)return;host.innerHTML=D.cetaCategories.map(c=>`<button class="ceta-outline-card" type="button" data-cat="${esc(c.id)}"><span>${esc(c.id)}.0</span><strong>${esc(c.title)}</strong><small>${c.count} competency row${c.count===1?'':'s'}</small></button>`).join('');host.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{$('#standard-track').value='CETa';$('#standard-category').value=b.dataset.cat;render();document.querySelector('.standards-filter')?.scrollIntoView({behavior:'smooth',block:'start'})})}
fillCats();const requested=new URLSearchParams(location.search).get('standard');if(requested)$('#standard-search').value=requested;renderCetaOutline();['#standard-track','#standard-category','#standard-status','#standard-search'].forEach(s=>$(s).oninput=render);renderSummary();render();
$('#source-evidence').innerHTML=D.meta.sources.map(s=>`<article><strong>${esc(s.title)}</strong><span>${esc(s.kind)}</span><p>${esc(s.note)}</p><a href="${esc(s.url)}" target="_blank" rel="noopener">Open source ↗</a></article>`).join('');
})();
