(()=>{
const D=window.ALFRED_ASSESSMENT||{}, $=(s,r=document)=>r.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='alfred-u-progress-v2';function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return {}}}function weekObj(v){return typeof v==='string'?{mastery:v,assessments:{}}:{mastery:v?.mastery||'',assessments:v?.assessments||{}}}
function evidence(){const p=load(),m={};const absorb=a=>(a?.attempts||[]).forEach(at=>{(at.s||[]).forEach(row=>{const [id,cRaw,tRaw]=row;const c=Number(cRaw||0),t=row.length>=3?Math.max(1,Number(tRaw||1)):1;const x=m[id]??={id,total:0,correct:0,last:null,streak:0,history:[]};x.total+=t;x.correct+=c;x.history.push({ok:c===t,at:at.at});if(!x.last||new Date(at.at)>new Date(x.last))x.last=at.at})});Object.values(p.events||{}).forEach(e=>absorb(e?.assessments?.lesson));Object.values(p.weeks||{}).forEach(raw=>{const w=weekObj(raw);Object.values(w.assessments||{}).forEach(absorb)});Object.values(m).forEach(x=>{x.history.sort((a,b)=>new Date(a.at)-new Date(b.at));let s=0;for(let i=x.history.length-1;i>=0;i--){if(x.history[i].ok)s++;else break}x.streak=s;x.pct=Math.round(x.correct/x.total*100);const days=x.history.at(-1)?.ok?(s>=3?45:s===2?21:7):2;x.due=x.last?new Date(new Date(x.last).getTime()+days*86400000):null;});return m}
const ev=evidence();function status(s){const x=ev[s.id];if(!x)return 'Not Introduced';if(x.due&&x.due<=new Date())return 'Retention Due';if(x.total<2)return x.correct?'Learning':'Developing';if(x.pct>=85&&x.streak>=3)return 'Mastered';if(x.pct>=80&&x.streak>=2)return 'Proficient';return 'Developing'}
function cls(x){return x.toLowerCase().replace(/\s+/g,'-')}
function renderSummary(){const all=[...D.cetaStandards,...D.careerStandards],counts={};all.forEach(s=>counts[status(s)]=(counts[status(s)]||0)+1);$('#standards-kpis').innerHTML=`<div><strong>${D.cetaStandards.length}</strong><span>CETa competency rows</span></div><div><strong>${D.careerStandards.length}</strong><span>career standards</span></div><div><strong>${counts.Mastered||0}</strong><span>mastered</span></div><div><strong>${counts['Retention Due']||0}</strong><span>retention due</span></div>`}
function render(){const track=$('#standard-track').value,cat=$('#standard-category').value,st=$('#standard-status').value,q=$('#standard-search').value.toLowerCase().trim(),base=track==='CETa'?D.cetaStandards:track==='Career'?D.careerStandards:[...D.cetaStandards,...D.careerStandards];const list=base.filter(s=>(!cat||s.category===cat)&&(!st||status(s)===st)&&(!q||`${s.code} ${s.text} ${s.categoryTitle}`.toLowerCase().includes(q)));$('#standard-count').textContent=`${list.length} standards shown`;$('#standard-list').innerHTML=list.map(s=>{const x=ev[s.id],z=status(s);return `<article class="standard-row"><div class="standard-code"><span>${esc(s.track)}</span><strong>${esc(s.code)}</strong></div><div class="standard-body"><div class="standard-title-row"><h3>${esc(s.categoryTitle)}</h3><span class="mastery-pill ${cls(z)}">${esc(z)}</span></div><p>${esc(s.text)}</p><div class="standard-evidence"><span>${esc(s.sourceChapter||'')}</span>${x?`<span>${x.correct}/${x.total} correct · ${x.pct}%</span><span>Last ${new Date(x.last).toLocaleDateString()}</span><span>Next retrieval ${x.due.toLocaleDateString()}</span>`:'<span>No assessment evidence yet</span>'}</div></div></article>`}).join('')||'<p class="empty-state">No standards match.</p>';}
function fillCats(){const sel=$('#standard-category');D.cetaCategories.forEach(c=>sel.insertAdjacentHTML('beforeend',`<option value="${c.id}" data-track="CETa">CETa ${c.id}.0 · ${esc(c.title)}</option>`));D.careerDomains.forEach(c=>sel.insertAdjacentHTML('beforeend',`<option value="${c.id}" data-track="Career">Career ${c.id} · ${esc(c.title)}</option>`));}
function renderCetaOutline(){const host=$('#ceta-outline-grid');if(!host)return;host.innerHTML=D.cetaCategories.map(c=>`<button class="ceta-outline-card" type="button" data-cat="${esc(c.id)}"><span>${esc(c.id)}.0</span><strong>${esc(c.title)}</strong><small>${c.count} competency row${c.count===1?'':'s'}</small></button>`).join('');host.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{$('#standard-track').value='CETa';$('#standard-category').value=b.dataset.cat;render();document.querySelector('.standards-filter')?.scrollIntoView({behavior:'smooth',block:'start'});});}
fillCats();renderCetaOutline();['#standard-track','#standard-category','#standard-status','#standard-search'].forEach(s=>$(s).oninput=render);renderSummary();render();
$('#source-evidence').innerHTML=D.meta.sources.map(s=>`<article><strong>${esc(s.title)}</strong><span>${esc(s.kind)}</span><p>${esc(s.note)}</p><a href="${esc(s.url)}" target="_blank" rel="noopener">Open source ↗</a></article>`).join('');
})();
