(()=>{
const E=window.ALFRED_EVENTS||[],W=window.ALFRED_WEEKS||[],A=window.ALFRED_ACADEMIC||{},D=window.ALFRED_ASSESSMENT||{},C=window.ALFRED_CURRICULUM||{},SG=window.ALFRED_CETA_STUDY_GUIDE||{},MC=window.AlfredMediaConsumption||{},G=window.ALFRED_GLOSSARY||[],R=window.ALFRED_RESOURCES||[];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STUDY_KEY='alfred-u-study-v13', PROGRESS_KEY='alfred-u-progress-v2', QUIET_KEY='alfred-u-quiet-mode', SYNC_KEY='alfred-u-sync-config-v1';
const now=()=>new Date();
const startOfDay=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x;};
const fmtDate=(v,o={weekday:'short',month:'short',day:'numeric'})=>new Intl.DateTimeFormat('en-US',o).format(new Date(v));
const cleanTitle=e=>String(e?.summary||'').replace(/^AU-ESET 301 \| /,'');
const css=document.createElement('link');css.rel='stylesheet';css.href='study-v2.css?v=16.3.50';document.head.appendChild(css);

function defaultState(){return {version:19,defaultMode:'standard',reviews:{},parking:[],parkingTombstones:{},parkingRecordTimes:{},history:[],sessionConfidence:{},session:null,lastWeek:null,library:{view:'review',reviewIndex:0,flashIndex:0,flashRevealed:false}};}
function load(){try{const raw=JSON.parse(localStorage.getItem(STUDY_KEY)||'null')||{};const base=defaultState();const merged={...base,...raw,library:{...base.library,...(raw.library||{})}};return window.AlfredParkingSync?.normalizeStudyState?.(merged)||merged;}catch{return defaultState();}}
let state=load();
if(state.session&&!Array.isArray(state.session.conceptIds))state.session=null;
function save(){state=window.AlfredParkingSync?.normalizeStudyState?.(state)||state;localStorage.setItem(STUDY_KEY,JSON.stringify({version:19,defaultMode:state.defaultMode,parking:state.parking||[],parkingTombstones:state.parkingTombstones||{},parkingRecordTimes:state.parkingRecordTimes||{},history:(state.history||[]).slice(0,100),session:state.session||null,lastWeek:Number(state.lastWeek)||null,library:state.library||defaultState().library}));}
function progress(){try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null')||{events:{},weeks:{},readiness:{},recordTimes:{}};}catch{return {events:{},weeks:{},readiness:{},recordTimes:{}};}}
function currentWeek(){const requested=Number(new URLSearchParams(location.search).get('week')||0);if(requested&&W.some(w=>Number(w.week)===requested))return requested;return window.AlfredState?.currentWeek?.()||1;}
function weekData(n){return W.find(w=>Number(w.week)===Number(n))||{};}
function eventStatus(id){const status=progress().events?.[String(id)]?.status;return status==='review'?'in-progress':status||'not-started';}
function targetEvent(){
  const params=new URLSearchParams(location.search),q=params.get('event');if(q){const hit=E.find(e=>String(e.id)===q);if(hit)return hit;}
  const week=currentWeek(), incomplete=e=>eventStatus(e.id)!=='complete';
  const inWeek=E.filter(e=>Number(e.week)===week&&e.type!=='Equipment').sort((a,b)=>new Date(a.start)-new Date(b.start));
  return inWeek.find(incomplete)||inWeek[0]||E.filter(incomplete).sort((a,b)=>new Date(a.start)-new Date(b.start))[0]||null;
}
let target=targetEvent(),step=0,activeMode=state.defaultMode||'standard',reviewedThisBlock=0,reviewLimit=3;
const studyMediaFilter={query:'',category:'all',type:'all',track:'all'};

function weekRecord(p,week){const raw=p.weeks?.[week]??p.weeks?.[String(week)];return typeof raw==='string'?{mastery:raw}:{...(raw||{})};}
function classroomStage(week){
  const w=weekRecord(progress(),week),l=w.learning||{},order=['orientation','ceta-lesson','career-lesson','media','practice','application','mastery'];
  if(l.currentStage&&order.includes(l.currentStage)&&!l.completed?.[l.currentStage])return l.currentStage;
  const next=order.find(id=>!l.completed?.[id]);return next==='orientation'?'ceta-lesson':next||'mastery';
}
const stageLabels={orientation:'Start Here','ceta-lesson':'Subject 1 · CETa lesson','career-lesson':'Subject 2 · Career lesson',media:'Teaching Media',practice:'Guided Practice',application:'Lab / Application',mastery:'Weekly Mastery'};

const stageOrder=['orientation','ceta-lesson','career-lesson','media','practice','application','mastery'];
function moduleForWeek(week){return (C.modules||[]).find(m=>Number(m.week)===Number(week))||null;}
function reachedTeachingCount(week,lessonIndex){
  const module=moduleForWeek(week),lesson=module?.lessons?.[lessonIndex],all=lesson?.integrated?.teaching||[],sections=all.filter(x=>!x.hiddenFromLesson);if(!sections.length)return 0;
  const w=weekRecord(progress(),week),l=w.learning||{},stageId=lessonIndex===0?'ceta-lesson':'career-lesson',stagePos=stageOrder.indexOf(stageId),currentPos=stageOrder.indexOf(l.currentStage||'orientation');
  if(l.completed?.[stageId]||currentPos>stagePos)return sections.length;
  const rec=l.lessonSegments?.[`lesson-${lessonIndex}`];
  if(rec){let furthest=Math.max(0,Number(rec.furthest??rec.current??0));if(Number(week)===4&&Number(lessonIndex)===0&&Number(rec.total)>0&&furthest>5)furthest-=1;return Math.min(sections.length,furthest);}
  if(l.currentStage===stageId)return 0;
  return 0;
}
function reachedStudySections(week=currentWeek()){
  const module=moduleForWeek(week);if(!module)return [];
  const out=[];(module.lessons||[]).forEach((lesson,lessonIndex)=>{
    const sections=(lesson?.integrated?.teaching||[]).map((section,rawIndex)=>({section,rawIndex})).filter(x=>!x.section.hiddenFromLesson),count=reachedTeachingCount(week,lessonIndex);
    sections.slice(0,count).forEach(({section,rawIndex},sectionIndex)=>out.push({week,lessonIndex,sectionIndex,rawIndex,lessonTitle:lesson.title||`Lesson ${lessonIndex+1}`,track:lesson.track||'',section}));
  });return out;
}
function reachedCorpus(week=currentWeek()){
  return reachedStudySections(week).map(x=>`${x.section.title||''} ${x.section.buildOn||''} ${x.section.text||''} ${x.section.remember||''}`).join(' ').toLowerCase();
}
function tokenize(text){const stop=new Set(['this','that','with','from','into','when','what','your','then','than','they','them','their','there','will','have','has','does','also','only','week','course','alfred','using','used','use','work','working','through','about','after','before','between','where','which','while','because','each','other','same','more','less','some','very','make','made','like','just','need','still']);return [...new Set(String(text||'').toLowerCase().replace(/[^a-z0-9µΩ]+/g,' ').split(/\s+/).filter(x=>x.length>3&&!stop.has(x)))];}
function overlapScore(a,b){const bs=new Set(tokenize(b));return tokenize(a).reduce((n,t)=>n+(bs.has(t)?1:0),0);}
function paragraphs(text){return String(text||'').split(/\n\s*\n/).filter(Boolean).map(x=>`<p>${esc(x.trim())}</p>`).join('');}
function shortText(text,max=420){const clean=String(text||'').replace(/\s+/g,' ').trim();return clean.length<=max?clean:`${clean.slice(0,max).replace(/\s+\S*$/,'')}…`;}
function renderStudyFigure(figure){
  if(!figure)return '';
  const provenance=figure.provenance==='source'?'Real/source visual':figure.provenance==='source-grounded'?'Source-grounded technical visual':figure.provenance==='alfred-model'?'Alfred instructional model':'';
  const head=`<figcaption><strong>${esc(figure.number||'Reference visual')} · ${esc(figure.title||'')}</strong>${provenance?`<span class="study-figure-provenance">${esc(provenance)}</span>`:''}</figcaption>`;
  const sourceLine=figure.source?`<p class="study-figure-source"><strong>Source:</strong> ${esc(figure.source)}</p>`:'';
  const sourceLinks=[figure.sourceUrl?`<a href="${esc(figure.sourceUrl)}" target="_blank" rel="noopener">Primary source →</a>`:'',figure.secondaryUrl?`<a href="${esc(figure.secondaryUrl)}" target="_blank" rel="noopener">Second source →</a>`:'',figure.tertiaryUrl?`<a href="${esc(figure.tertiaryUrl)}" target="_blank" rel="noopener">Third source →</a>`:'',figure.licenseUrl?`<a href="${esc(figure.licenseUrl)}" target="_blank" rel="noopener">License →</a>`:''].filter(Boolean).join(' ');
  if(figure.type==='table')return `<figure class="study-review-figure">${head}<div class="study-reference-table"><table><thead><tr>${(figure.columns||[]).map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${(figure.rows||[]).map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${figure.caption?`<p>${esc(figure.caption)}</p>`:''}${sourceLine}${sourceLinks?`<div class="study-figure-links">${sourceLinks}</div>`:''}</figure>`;
  if(figure.type==='flow'){const steps=figure.steps||[];return `<figure class="study-review-figure">${head}<div class="source-figure-flow study-figure-flow" role="group" aria-label="${esc(figure.title||'Instructional flow')}">${steps.map((step,i)=>`<div class="source-flow-step"><span>${i+1}</span><div><strong>${esc(step.title||`Step ${i+1}`)}</strong><p>${esc(step.body||'')}</p></div></div>${i<steps.length-1?'<span class="source-flow-arrow" aria-hidden="true">→</span>':''}`).join('')}</div>${figure.caption?`<p>${esc(figure.caption)}</p>`:''}${sourceLine}${sourceLinks?`<div class="study-figure-links">${sourceLinks}</div>`:''}</figure>`;}
  if(figure.type==='gallery'){const items=figure.items||[];return `<figure class="study-review-figure">${head}<div class="source-figure-gallery study-figure-gallery">${items.map(item=>`<article class="source-gallery-item"><a href="${esc(item.src||'#')}" target="_blank" rel="noopener noreferrer"><img src="${esc(item.src||'')}" alt="${esc(item.alt||item.label||'Course source image')}" loading="lazy" referrerpolicy="no-referrer"></a><div class="source-gallery-meta"><strong>${esc(item.label||'Source image')}</strong>${item.credit?`<span>${esc(item.credit)}</span>`:''}<div class="source-gallery-links">${item.sourceUrl?`<a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">Image source →</a>`:''}${item.license?`<span>${esc(item.license)}</span>`:''}${item.licenseUrl?`<a href="${esc(item.licenseUrl)}" target="_blank" rel="noopener">License →</a>`:''}</div></div></article>`).join('')}</div>${figure.caption?`<p>${esc(figure.caption)}</p>`:''}${sourceLine}${sourceLinks?`<div class="study-figure-links">${sourceLinks}</div>`:''}</figure>`;}
  if(figure.src)return `<figure class="study-review-figure"><img src="${esc(figure.src)}" alt="${esc(figure.alt||figure.title||'Course figure')}" loading="lazy" referrerpolicy="no-referrer">${head}${figure.caption?`<p>${esc(figure.caption)}</p>`:''}${sourceLine}${sourceLinks?`<div class="study-figure-links">${sourceLinks}</div>`:''}</figure>`;
  return '';
}
function studyFlashcards(week=currentWeek()){
  return reachedStudySections(week).map((x,i)=>({id:`lesson-${x.lessonIndex}-section-${x.sectionIndex}`,title:x.section.title||`Concept ${i+1}`,track:x.track,lessonTitle:x.lessonTitle,front:`Explain this idea in your own words: ${x.section.title||`Concept ${i+1}`}`,back:x.section.remember||shortText(x.section.text,560),buildOn:x.section.buildOn||''}));
}
function reachedMedia(week=currentWeek()){
  const sections=reachedStudySections(week),corpus=reachedCorpus(week),arch=C.teachingMediaArchitecture;if(!sections.length||!arch?.assignments)return [];
  const rows=Object.values(arch.assignments).filter(a=>a.destination==='study'&&Number(a.studyWeek||a.assignmentWeek)===Number(week));
  const totalTeaching=(moduleForWeek(week)?.lessons||[]).reduce((n,l)=>n+(l?.integrated?.teaching||[]).filter(x=>!x.hiddenFromLesson).length,0),allReached=sections.length>=totalTeaching&&totalTeaching>0;
  return rows.map((a,i)=>{
    const sourceMeta=C.sources?.[a.source]||{};
    const origin=C.modules?.find(m=>Number(m.week)===Number(a.assignmentWeek));
    const media=(origin?.integration?.media||[]).find(x=>x.source===a.source)||{};
    const text=`${media.role||''} ${media.use||''} ${media.watchFor||''} ${sourceMeta.title||''} ${a.studyCategory||''}`;
    const score=overlapScore(text,corpus);
    return {...media,source:a.source,sourceMeta,score,index:i,architecture:a,studyCategory:a.studyCategory||'Alternate Explanation',studyWeek:Number(a.studyWeek||a.assignmentWeek),originWeek:Number(a.assignmentWeek)};
  }).filter(x=>allReached||x.score>=1).sort((a,b)=>b.score-a.score||a.index-b.index);
}
function reachedGlossary(week=currentWeek()){
  const corpus=` ${reachedCorpus(week).replace(/[^a-z0-9µΩ]+/g,' ')} `;return (G||[]).map(g=>{const term=String(g.term||'').toLowerCase();const normalized=` ${term.replace(/[^a-z0-9µΩ]+/g,' ')} `;const present=term.length>=3&&corpus.includes(normalized);return {...g,present};}).filter(x=>x.present).slice(0,36);
}
function reachedKnowledge(week=currentWeek()){
  const corpus=reachedCorpus(week);return (A.knowledge||[]).filter(k=>(k.weeks||[]).map(Number).includes(Number(week))&&overlapScore(`${k.term||''} ${k.keywords||''}`,corpus)>0).slice(0,18);
}
function reachedResources(week=currentWeek()){
  const corpus=reachedCorpus(week);return (R||[]).filter(r=>(r.weeks||[]).map(Number).includes(Number(week))).map(r=>({...r,score:overlapScore(`${r.title||''} ${(r.contexts||[]).join(' ')} ${r.category||''}`,corpus)})).filter(r=>r.score>0||/CETa \/ Official/i.test(r.category||'')).sort((a,b)=>b.score-a.score).slice(0,10);
}
function libraryView(){return state.library?.view||'review';}
function setLibraryView(view){
  state.library=state.library||defaultState().library;state.library.view=view;state.lastWeek=currentWeek();save();renderStudyLibrary();
  try{const u=new URL(location.href);u.searchParams.set('view',view);history.replaceState(null,'',u);}catch{}
}
function renderReachedSummary(){
  const out=$('#study-reached-summary');if(!out)return;const week=currentWeek(),sections=reachedStudySections(week),module=moduleForWeek(week),ceta=sections.filter(x=>x.lessonIndex===0).length,career=sections.filter(x=>x.lessonIndex===1).length;
  out.innerHTML=sections.length?`<strong>Week ${String(week).padStart(2,'0')} · ${esc(module?.title||weekData(week).topic||'Current week')}</strong><span>${sections.length} teaching section${sections.length===1?'':'s'} available to study · ${ceta} CETa${career?` · ${career} Career`:''}</span>`:`<strong>Week ${String(week).padStart(2,'0')}</strong><span>Complete the first teaching section in Classroom, then it will appear here for study.</span>`;
}
function renderReviewMaterial(){
  const sections=reachedStudySections(),out=$('#study-material-content');if(!out)return;if(!sections.length){out.innerHTML='<div class="study-library-empty"><strong>No teaching section has been reached yet.</strong><p>Open Classroom and complete the first teaching section. Study will automatically unlock that material here without exposing future content.</p><a class="button green" href="learn.html">Open Classroom →</a></div>';return;}
  state.library=state.library||defaultState().library;let i=Math.max(0,Math.min(Number(state.library.reviewIndex)||0,sections.length-1));state.library.reviewIndex=i;const x=sections[i],sec=x.section;
  out.innerHTML=`<article class="study-review-sheet"><header><div><span>${esc(x.track||`Lesson ${x.lessonIndex+1}`)} · Review ${i+1} of ${sections.length}</span><h3>${esc(sec.title)}</h3><p>${esc(x.lessonTitle)}</p></div><a class="text-link" href="learn.html?week=${x.week}">Open full Classroom →</a></header>${sec.buildOn?`<aside class="study-builds-on"><strong>Build this on</strong><p>${esc(sec.buildOn)}</p></aside>`:''}<section class="study-quick-read"><span>Quick re-read</span><p>${esc(sec.remember||shortText(sec.text,460))}</p></section><section class="study-full-read"><div class="study-subhead"><span>Full review text</span><small>Read it again as many times as you need. Nothing here is graded.</small></div>${paragraphs(sec.text)}</section>${renderStudyFigure(sec.figure)}${sec.remember?`<aside class="study-hold-on"><strong>Hold onto this</strong><p>${esc(sec.remember)}</p></aside>`:''}<div class="study-repetition-cue"><strong>One useful study pass</strong><ol><li>Read the Quick re-read once.</li><li>Read the full explanation slowly.</li><li>Look away and say the idea in plain language.</li><li>Read the Hold onto this box again and compare.</li></ol></div><nav class="study-library-nav"><button type="button" class="button outline-green" id="study-review-prev" ${i===0?'disabled':''}>← Previous review</button><span>${i+1} / ${sections.length}</span><button type="button" class="button green" id="study-review-next" ${i===sections.length-1?'disabled':''}>Next review →</button></nav></article>`;
  $('#study-review-prev')?.addEventListener('click',()=>{state.library.reviewIndex=Math.max(0,i-1);save();renderStudyLibrary();$('#study-material-workspace')?.scrollIntoView({behavior:'smooth',block:'start'});});
  $('#study-review-next')?.addEventListener('click',()=>{state.library.reviewIndex=Math.min(sections.length-1,i+1);save();renderStudyLibrary();$('#study-material-workspace')?.scrollIntoView({behavior:'smooth',block:'start'});});
}
function renderFlashcards(){
  const cards=studyFlashcards(),out=$('#study-material-content');if(!out)return;if(!cards.length){out.innerHTML='<div class="study-library-empty"><strong>No concept cards yet.</strong><p>Reach a teaching section in Classroom first.</p></div>';return;}
  state.library=state.library||defaultState().library;let i=Math.max(0,Math.min(Number(state.library.flashIndex)||0,cards.length-1));state.library.flashIndex=i;const c=cards[i],revealed=!!state.library.flashRevealed;
  out.innerHTML=`<section class="study-flashcard-shell"><div class="study-view-intro"><span>Concept Flashcards · ${i+1} of ${cards.length}</span><h3>Use the answer side to study—not only to test.</h3><p>Read the front, try to say what you know if you can, then reveal the back immediately when you need it. Vocabulary-only cards remain available in the Vocabulary Study Lab below.</p></div><article class="study-concept-card ${revealed?'revealed':''}" id="study-concept-card"><span>${esc(c.track||'Course concept')}</span><h3>${esc(c.title)}</h3><p class="flash-front">${esc(c.front)}</p>${revealed?`<div class="flash-back"><strong>Study answer</strong><p>${esc(c.back)}</p>${c.buildOn?`<small>Connection: ${esc(c.buildOn)}</small>`:''}</div>`:'<div class="flash-covered"><span>Answer hidden</span></div>'}<button type="button" class="button ${revealed?'outline-green':'gold'}" id="study-flash-reveal">${revealed?'Hide answer':'Reveal study answer'}</button></article><nav class="study-library-nav"><button type="button" class="button outline-green" id="study-flash-prev" ${i===0?'disabled':''}>← Previous card</button><span>${i+1} / ${cards.length}</span><button type="button" class="button green" id="study-flash-next" ${i===cards.length-1?'disabled':''}>Next card →</button></nav></section>`;
  $('#study-flash-reveal')?.addEventListener('click',()=>{state.library.flashRevealed=!state.library.flashRevealed;save();renderStudyLibrary();});
  $('#study-flash-prev')?.addEventListener('click',()=>{state.library.flashIndex=Math.max(0,i-1);state.library.flashRevealed=false;save();renderStudyLibrary();});
  $('#study-flash-next')?.addEventListener('click',()=>{state.library.flashIndex=Math.min(cards.length-1,i+1);state.library.flashRevealed=false;save();renderStudyLibrary();});
}
function guideStudyCards(week=currentWeek()){
  const reached=reachedStudySections(week),allTeaching=(moduleForWeek(week)?.lessons||[]).reduce((n,l)=>n+(l?.integrated?.teaching||[]).filter(x=>!x.hiddenFromLesson).length,0),allReached=reached.length>=allTeaching&&allTeaching>0;
  const reachedKeys=new Set(reached.map(x=>`${x.lessonIndex}:${x.section.sectionId||`concept-${x.rawIndex+1}`}`));
  return (SG.recordsForWeek?.(week)||[]).filter(r=>r.classification!=='required').filter(r=>allReached||!(r.placements||[]).length||(r.placements||[]).some(p=>reachedKeys.has(`${p.lesson}:${p.segment}`))).map(r=>({guide:true,record:r,studyCategory:r.studyCategory||'Review',sourceMeta:{title:`Associate CET Study Guide · Chapter ${r.chapter} · ${SG.pageLabel?.(r)||''}`,kind:'Study Guide',org:'ETA International'},architecture:{track:r.track||'ceta'},originWeek:r.week}));
}
function guideStudyCard(r){const err=(SG.errataFor?.(r)||[]).map(x=>`<aside class="study-guide-errata"><strong>⚠ ${esc(x.label)}</strong><p>${esc(x.correction)}</p><a href="${esc(x.sourceUrl)}" target="_blank" rel="noopener">Official errata ↗</a></aside>`).join(''),first=(r.pageGroups||[])[0]?.[0]||1,p=SG.primaryPlacement?.(r),href=p?`learn.html?week=${p.week}&stage=${p.lesson===0?'ceta-lesson':'career-lesson'}&lesson=${p.lesson}&section=${encodeURIComponent(p.segment)}`:`learn.html?week=${r.week}&stage=media`,consumption=MC.controlHTML?.({week:r.week,id:MC.guideId?.(r.id),kind:'study-guide'})||'';return `<article class="study-media-card study-guide-card" data-study-media-card data-study-media-category="${esc(r.studyCategory||'Review')}" data-study-media-type="Study Guide" data-study-media-track="${esc(r.track||'ceta')}"><span>${esc(r.studyCategory||'Review')}</span><h4>Associate CET Study Guide · Chapter ${esc(r.chapter)} · ${esc(SG.pageLabel?.(r)||'')}</h4><small>Sixth Edition · private book locator</small><p><strong>Use it when:</strong> ${esc(r.purpose)}</p><p><strong>Focus on:</strong> ${esc(r.focus)}</p>${r.authorityNote?`<aside class="study-guide-authority"><strong>Current-source note</strong><p>${esc(r.authorityNote)}</p></aside>`:''}${err}<div class="study-guide-private-controls"><span data-private-guide-state>Private copy not connected on this device</span><button class="button outline-green" type="button" data-private-guide-choose>Connect private PDF on this device</button><button class="button outline-green" type="button" data-private-guide-open data-printed-page="${first}" hidden>Open private copy to page ↗</button></div>${consumption}<a class="text-link" href="${href}">Open mapped Alfred lesson →</a></article>`;}

function renderMediaStudy(){
  const out=$('#study-material-content'),media=reachedMedia(),guides=guideStudyCards(),items=[...media,...guides];if(!out)return;if(!reachedStudySections().length){out.innerHTML='<div class="study-library-empty"><strong>No reached material yet.</strong><p>Study media will appear after Classroom teaches the relevant material.</p></div>';return;}
  const categories=[...new Set(items.map(x=>x.studyCategory).filter(Boolean))].sort();
  const typeOf=x=>x.guide?'Study Guide':/video|lecture/i.test(String(x.sourceMeta?.kind||''))?'Video':/interactive|simulation|tool/i.test(String(x.sourceMeta?.kind||''))?'Interactive / Tool':/course|training|mooc/i.test(String(x.sourceMeta?.kind||''))?'Course':'Written / Reference';
  const types=[...new Set(items.map(typeOf))].sort(),tracks=[...new Set(items.map(x=>x.architecture?.track||'ceta'))].sort(),options=(arr,current)=>arr.map(x=>`<option value="${esc(x)}"${current===x?' selected':''}>${esc(x)}</option>`).join('');
  const cards=items.map(m=>m.guide?guideStudyCard(m.record):(()=>{const type=typeOf(m),kind=type==='Video'?'video':type==='Interactive / Tool'?'interactive':type==='Written / Reference'?'reading':'reference',consumption=MC.controlHTML?.({week:m.originWeek,id:MC.mediaId?.(m.originWeek,m.source),kind})||'';return `<article class="study-media-card" data-study-media-card data-study-media-category="${esc(m.studyCategory)}" data-study-media-type="${esc(type)}" data-study-media-track="${esc(m.architecture?.track||'ceta')}"><span>${esc(m.studyCategory)}</span><h4>${esc(m.sourceMeta?.title||m.source||'Course media')}</h4><small>${esc(m.sourceMeta?.org||m.sourceMeta?.kind||'Verified course source')}${m.originWeek!==Number(currentWeek())?` · originally W${String(m.originWeek).padStart(2,'0')}`:''}</small>${m.use?`<p><strong>Use it when:</strong> ${esc(m.use)}</p>`:''}${m.watchFor?`<p><strong>Focus on:</strong> ${esc(m.watchFor)}</p>`:''}${m.sourceMeta?.url?`<a class="button outline-green" href="${esc(m.sourceMeta.url)}" target="_blank" rel="noopener">Open study source ↗</a>`:'<span class="small-note">Use the exact route/version-specific source identified by the task.</span>'}${consumption}</article>`})()).join('');
  out.innerHTML=`<section class="study-media-library"><div class="study-view-intro"><span>Help on demand</span><h3>Use another explanation only when you need it.</h3><p>Study Guide review pages, alternate explanations, demonstrations, troubleshooting, and deeper resources live here after the relevant instruction has been reached.</p></div>${items.length?`<div class="resource-filters study-media-filters"><label>Search<input id="study-media-search" type="search" value="${esc(studyMediaFilter.query)}" placeholder="Example: op amp, UART, troubleshooting…"></label><label>Need<select id="study-media-category"><option value="all">All needs</option>${options(categories,studyMediaFilter.category)}</select></label><label>Format<select id="study-media-type"><option value="all">All formats</option>${options(types,studyMediaFilter.type)}</select></label><label>Track<select id="study-media-track"><option value="all">All tracks</option>${options(tracks,studyMediaFilter.track)}</select></label></div><p class="small-note" id="study-media-count">${items.length} study resource${items.length===1?'':'s'} available for Week ${String(currentWeek()).padStart(2,'0')}.</p><div class="study-media-grid">${cards}</div><div class="study-library-empty" id="study-media-empty" hidden><strong>No Study resources match those filters.</strong></div>`:'<div class="study-library-empty"><strong>No extra media are assigned here.</strong></div>'}</section>`;
  function apply(){const q=String($('#study-media-search')?.value||'').trim().toLowerCase(),cat=$('#study-media-category')?.value||'all',type=$('#study-media-type')?.value||'all',track=$('#study-media-track')?.value||'all';Object.assign(studyMediaFilter,{query:q,category:cat,type,track});let shown=0;$$('[data-study-media-card]',out).forEach(card=>{const ok=(!q||card.textContent.toLowerCase().includes(q))&&(cat==='all'||card.dataset.studyMediaCategory===cat)&&(type==='all'||card.dataset.studyMediaType===type)&&(track==='all'||card.dataset.studyMediaTrack===track||card.dataset.studyMediaTrack==='both');card.hidden=!ok;if(ok)shown++;});const count=$('#study-media-count'),empty=$('#study-media-empty');if(count)count.textContent=`Showing ${shown} of ${items.length} Study resources for Week ${String(currentWeek()).padStart(2,'0')}.`;if(empty)empty.hidden=shown!==0;}['#study-media-search','#study-media-category','#study-media-type','#study-media-track'].forEach(sel=>{const el=$(sel);el?.addEventListener(el.type==='search'?'input':'change',apply);});apply();window.AlfredPrivateCetaGuide?.refreshControls?.();MC.bind?.(out);MC.refresh?.(out);
}

function renderReferenceStudy(){
  const out=$('#study-material-content');if(!out)return;const sections=reachedStudySections(),terms=reachedGlossary(),knowledge=reachedKnowledge(),resources=reachedResources();if(!sections.length){out.innerHTML='<div class="study-library-empty"><strong>No reached material yet.</strong><p>References will populate from concepts you encounter in Classroom.</p></div>';return;}
  out.innerHTML=`<section class="study-reference-library"><div class="study-view-intro"><span>Reference</span><h3>Keep the useful facts close while you study.</h3><p>This view pulls key glossary terms, formulas/knowledge notes, and assigned resources connected to material you have already reached.</p></div>${knowledge.length?`<div class="study-reference-knowledge"><h4>Key ideas &amp; formulas</h4>${knowledge.map(k=>`<article><strong>${esc(k.term)}</strong><p>${esc(k.summary||'')}</p>${k.deeper?`<p>${esc(k.deeper)}</p>`:''}${k.formula?`<code>${esc(k.formula)}</code>`:''}</article>`).join('')}</div>`:''}<div class="study-reference-columns"><div><h4>Glossary terms you have encountered</h4>${terms.length?`<div class="study-term-list">${terms.map(g=>`<a href="glossary.html#${esc(g.slug||String(g.term||'').toLowerCase().replace(/[^a-z0-9]+/g,'-'))}"><strong>${esc(g.term)}</strong><span>${esc(shortText(g.definition||g.plain||g.summary||'',120))}</span></a>`).join('')}</div>`:'<p>No matched glossary terms in the reached text yet.</p>'}<a class="text-link" href="glossary.html?view=all">Open complete Course Glossary →</a></div><div><h4>Assigned resources</h4>${resources.length?`<div class="study-resource-list">${resources.map(r=>`<a href="${esc(r.url)}" target="_blank" rel="noopener"><strong>${esc(r.title||r.domain)}</strong><span>${esc(r.category||r.domain||'Course resource')}</span></a>`).join('')}</div>`:'<p>No additional assigned resource matches this reached material yet.</p>'}<a class="text-link" href="resources.html">Open Engineering Library →</a></div></div></section>`;
}
function renderWeakAreasStudy(){
  const out=$('#study-material-content');if(!out)return;const week=currentWeek(),pool=conceptPool(week),latest=latestConceptRatings(week),due=new Set(dueConceptIds(week)),weak=pool.filter(c=>latest[c.id]==='red'||latest[c.id]==='yellow'||due.has(c.id));
  out.innerHTML=`<section class="study-weak-library"><div class="study-view-intro"><span>Work Weak Areas</span><h3>Study the places that have already shown friction.</h3><p>This is review-first. Use the explanation and then jump to Review Material, Flashcards, or Active Recall when you want to check it again.</p></div>${weak.length?`<div class="study-weak-grid">${weak.map(c=>`<article><span>${due.has(c.id)?'Due for memory review':latest[c.id]==='red'?'Previously missed':'Previously partial'}</span><h4>${esc(c.name)}</h4><p>${esc(c.repair||c.answer||'')}</p>${c.formula?`<code>${esc(c.formula)}</code>`:''}<div><button type="button" class="text-link" data-weak-review="review">Open Review Material</button><button type="button" class="text-link" data-weak-review="flashcards">Open Flashcards</button></div></article>`).join('')}</div>`:'<div class="study-library-empty"><strong>No weak areas are recorded yet.</strong><p>That is fine. You do not need to fail a question before you are allowed to study. Start with Review Material, Flashcards, Watch &amp; Review, or Reference.</p></div>'}</section>`;
  $$('[data-weak-review]').forEach(b=>b.addEventListener('click',()=>setLibraryView(b.dataset.weakReview)));
}
function renderStudyLibrary(){
  renderReachedSummary();const view=libraryView();$$('[data-study-view]').forEach(b=>{const on=b.dataset.studyView===view;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});
  const material=$('#study-material-workspace'),recall=$('#active-recall-section');if(view==='recall'){material?.classList.add('hidden');recall?.classList.remove('hidden');renderRecommendation();renderResumeSession();return;}material?.classList.remove('hidden');recall?.classList.add('hidden');
  if(view==='flashcards')renderFlashcards();else if(view==='media')renderMediaStudy();else if(view==='reference')renderReferenceStudy();else if(view==='weak')renderWeakAreasStudy();else renderReviewMaterial();
}

const WEEK1=[
 {id:'voltage',name:'Voltage',prompt:'Without notes: what is voltage physically, and why is a voltage measurement always between two points?',repair:'Voltage is electric potential difference: an energy-per-charge difference between two locations. Voltage does not flow. A meter reports the difference between its two probes, so every voltage value has an explicit or implied reference node.',formula:'1 V = 1 J/C',practice:'A node is labeled 3.3 V. What information is missing if no reference node has been stated?',answer:'The reference point is missing. “3.3 V” means 3.3 volts relative to some other node, commonly circuit common/ground.',keywords:'voltage potential difference reference node'},
 {id:'current',name:'Current',prompt:'Without notes: what does current measure, what is one ampere, and why is current described as going through a path?',repair:'Current is the rate at which electric charge passes a point. One ampere is one coulomb per second. Because it describes charge passing through a path, current is measured through a branch rather than across two nodes.',formula:'1 A = 1 C/s',practice:'If 3 coulombs of charge pass a point in 2 seconds, what is the average current? Explain the unit.',answer:'I = 3 C / 2 s = 1.5 A. The ampere means coulombs per second.',keywords:'current ampere charge flow'},
 {id:'resistance',name:'Resistance + Ohm’s law',prompt:'At a fixed voltage, what should happen to current if resistance doubles? Explain why before using an equation.',repair:'Resistance limits current for a given applied voltage. For an ohmic resistor, V = IR, so I = V/R. Holding V constant while doubling R makes the current half as large. Predicting this direction before calculating is a powerful error check.',formula:'V = IR · I = V/R · R = V/I',practice:'A 6 V source is across 2 kΩ. Predict the rough current first, then calculate it.',answer:'A few volts across a few kilohms should produce a few milliamps. I = 6 V / 2000 Ω = 0.003 A = 3 mA.',keywords:'resistance ohms law resistor'},
 {id:'prefixes',name:'SI prefixes + conversion',prompt:'Explain what kilo, milli, and micro actually mean as multipliers. Then convert 2.2 kΩ to Ω and 15 mA to A.',repair:'Prefixes are powers-of-ten multipliers attached to units. kilo k = 10³ = ×1000; milli m = 10⁻³ = ×0.001; micro µ = 10⁻⁶ = ×0.000001. “Move the decimal” is only the visible effect of multiplying or dividing by these factors.',formula:'k = 10³ · m = 10⁻³ · µ = 10⁻⁶',practice:'Convert 4700 Ω to kΩ and 250 µA to mA. State why each numerical value gets larger or smaller.',answer:'4700 Ω = 4.7 kΩ. 250 µA = 0.250 mA. When you express the same quantity in a larger unit, the numerical count becomes smaller.',keywords:'metric prefixes kilo milli micro conversion'},
 {id:'power',name:'Electrical power',prompt:'What does electrical power tell you physically, and why does multiplying voltage by current produce watts?',repair:'Power is the rate of energy transfer. Voltage is joules per coulomb and current is coulombs per second, so V × I gives joules per second, which is watts.',formula:'P = VI · 1 W = 1 J/s',practice:'A 5 V branch carries 20 mA. Find power in watts and milliwatts.',answer:'20 mA = 0.020 A. P = 5 V × 0.020 A = 0.100 W = 100 mW.',keywords:'power watts voltage current'},
 {id:'path',name:'Closed, open, and short paths',prompt:'Explain the difference between a closed circuit, an open circuit, and a short circuit. Why can a short produce very large current?',repair:'A closed circuit provides a complete path for steady current. An open breaks the path, so steady branch current falls essentially to zero. A short is an unintended very-low-resistance path; with the same source voltage, low resistance can allow very large current.',formula:'I = V/R explains why very low R can create high I',practice:'A switch opens a series circuit. What happens to branch current, and can voltage still exist across the open switch?',answer:'The steady branch current falls to essentially zero, but a voltage difference can still appear across the open switch.',keywords:'closed circuit open circuit short circuit'}
];

function requestedStandardConcept(){
  const id=new URLSearchParams(location.search).get('standard');if(!id)return null;
  const all=[...(D.cetaStandards||[]),...(D.careerStandards||[])],s=all.find(x=>String(x.id)===String(id));if(!s)return null;
  return {id:`standard-${s.id}`,name:s.categoryTitle||s.id,prompt:`Without notes, explain this competency: ${s.text}`,repair:s.text,formula:'',practice:`Give one concrete example, calculation, measurement, or troubleshooting action that would demonstrate ${s.id}.`,answer:'A strong answer should directly demonstrate the stated competency with a technically specific example or evidence route.',standardId:s.id,keywords:s.text};
}
function genericConcepts(week){
  return (A.knowledge||[]).filter(k=>(k.weeks||[]).map(Number).includes(Number(week))).map((k,i)=>({
    id:`kb-${String(k.term||i).toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,name:k.term||`Concept ${i+1}`,
    prompt:`Without notes, explain ${k.term}. What does it mean physically or technically, and how would you recognize or use it?`,
    repair:[k.summary,k.deeper].filter(Boolean).join(' '),formula:k.formula||'',
    practice:`Apply ${k.term} to one Week ${week} example: make a prediction, calculation, measurement plan, or troubleshooting decision and explain why it is reasonable.`,
    answer:k.deeper||k.summary||`Your answer should correctly define and apply ${k.term}.`,keywords:k.keywords||k.term
  }));
}
function conceptMatchesReached(c,week){const corpus=reachedStudySections(week).map(x=>`${x.section.title||''} ${x.section.remember||''}`).join(' ').toLowerCase();return !!corpus&&overlapScore(`${c.name||''} ${c.keywords||''}`,corpus)>0;}
function sectionDerivedConcepts(week){return reachedStudySections(week).map((x,i)=>({id:`section-${x.lessonIndex}-${x.sectionIndex}`,name:x.section.title||`Reached concept ${i+1}`,prompt:`Without notes, explain the main idea from “${x.section.title||`this section`}.”`,repair:x.section.remember||shortText(x.section.text,520),formula:'',practice:`Give one concrete example, prediction, measurement, or safety decision that uses ${x.section.title||'this concept'}.`,answer:x.section.remember||shortText(x.section.text,520),keywords:`${x.section.title||''} ${x.section.text||''}`}));}
function conceptPool(week){
  const requested=requestedStandardConcept();
  let filtered=[];
  if(Number(week)===1){const unlock={current:1,voltage:2,path:3,resistance:7,prefixes:5,power:9},count=reachedTeachingCount(1,0);filtered=WEEK1.filter(c=>count>Number(unlock[c.id]??999));}
  else filtered=genericConcepts(week).filter(c=>conceptMatchesReached(c,week));
  if(requested)return [requested,...filtered.filter(x=>x.id!==requested.id)];
  if(filtered.length)return filtered;
  return sectionDerivedConcepts(week);
}
function latestConceptRatings(week){
  const out={};for(const h of state.history||[]){if(Number(h.week)!==Number(week)||!h.ratings)continue;for(const [id,r] of Object.entries(h.ratings))if(!(id in out))out[id]=r;}return out;
}
function dueConceptIds(week){
  const w=weekRecord(progress(),week),out=[];
  for(const [id,r] of Object.entries(w.reviewQueue||{}))if(r?.source==='study-session-v2'&&Date.parse(r.due||0)<=Date.now())out.push(String(r.conceptId||id).replace(/^study:w\d+:/,''));
  return out;
}
function chooseConcepts(week,mode){
  const pool=conceptPool(week),limit=mode==='quick'?3:mode==='deep'?6:5,latest=latestConceptRatings(week),due=new Set(dueConceptIds(week));
  return pool.slice().sort((a,b)=>{
    const score=x=>due.has(x.id)?0:latest[x.id]==='red'?1:latest[x.id]==='yellow'?2:latest[x.id]==='green'?4:3;
    return score(a)-score(b);
  }).slice(0,Math.min(limit,pool.length));
}
function conceptById(id,week=state.session?.week||currentWeek()){return conceptPool(week).find(x=>x.id===id);}

function renderRecommendation(){
  const box=$('#recommended-session'),start=$('#start-study-session');if(!box)return;
  const week=currentWeek(),concepts=conceptPool(week),sections=reachedStudySections(week),due=dueConceptIds(week).filter(id=>concepts.some(c=>c.id===id)).length;
  target=targetEvent();
  if(start){start.disabled=!concepts.length;start.dataset.routeHref='';start.textContent='Start Active Recall';}
  const fieldset=$('.study-start-controls fieldset'),note=$('.study-start-controls .small-note');if(fieldset)fieldset.classList.remove('hidden');
  if(note)note.textContent=concepts.length?'Study first if you need to. Active Recall only uses material you have already reached, and its ratings schedule review without changing course mastery.':'Reach at least one teaching section in Classroom first. Alfred will not test you on material that has not appeared in your learning path.';
  if(!sections.length){box.innerHTML=`<div class="recommended-label">Week ${String(week).padStart(2,'0')} · No reached teaching sections yet</div><h2>Nothing to test yet—and that is okay.</h2><p>Active Recall is a memory check after learning. Complete the first Classroom teaching section, then return here when you want to test what stuck.</p>`;return;}
  box.innerHTML=`<div class="recommended-label">Week ${String(week).padStart(2,'0')} · ${concepts.length} reached concept${concepts.length===1?'':'s'}${due?` · ${due} due`:''}</div><h2>Check your memory when you are ready.</h2><p>This is the existing retrieval → diagnose → repair → practice → teach-back workflow, now limited to concepts you have already encountered. You can leave and return to Review Material at any time.</p><div class="recommended-meta"><span>${sections.length} reached teaching section${sections.length===1?'':'s'}</span><span>${due?`${due} spaced review${due===1?'':'s'} due`:'No spaced review due right now'}</span></div>`;
}
function renderWeeklyPlan(){
  const out=$('#weekly-plan');if(!out)return;const week=currentWeek(),wd=weekData(week),list=E.filter(e=>Number(e.week)===Number(week)),mins=list.filter(e=>e.type!=='Equipment').reduce((a,e)=>{const s=new Date(e.start),en=new Date(e.end);return a+Math.max(0,Math.round((en-s)/60000));},0),lab=list.find(e=>e.type==='Lab'||e.type==='Project');
  const link=$('#open-week-module');if(link){link.href=`learn.html?week=${week}`;link.textContent='Open complete Classroom →';}
  out.innerHTML=`<article class="weekly-plan-main"><div class="week-kicker">Week ${String(week).padStart(2,'0')}</div><h3>${esc(wd.topic||'Current Week')}</h3><p><strong>Scheduled course time:</strong> ${Math.round(mins/60*10)/10} hours</p><div class="three-priorities">${(wd.outcomes||[]).slice(0,3).map((x,i)=>`<div><span>${i+1}</span><p>${esc(x)}</p></div>`).join('')}</div></article><article class="weekly-plan-side"><h3>Study supports Classroom</h3><p>Use Study to reread, review, watch, reference, and rehearse material you have already reached. Classroom remains the authoritative first-teaching sequence and completion path.</p>${lab?`<div class="weekly-lab"><strong>Hands-on block</strong><span>${esc(cleanTitle(lab))}</span></div>`:''}<div class="mastery-readout"><strong>Need evidence?</strong> <a href="analytics.html">Open Mastery →</a></div></article>`;
}

function sessionStageNames(){return ['Retrieve','Diagnose','Repair','Practice','Teach Back','Next Move'];}
function sessionConcepts(){return (state.session?.conceptIds||[]).map(id=>conceptById(id,state.session.week)).filter(Boolean);}
function weakConcepts(){const s=state.session||{},cs=sessionConcepts();return cs.filter(c=>s.ratings?.[c.id]!=='green');}
function practiceConcepts(){const s=state.session||{},weak=weakConcepts(),all=sessionConcepts(),limit=s.mode==='quick'?1:s.mode==='deep'?3:2;return [...weak,...all.filter(x=>!weak.some(w=>w.id===x.id))].slice(0,Math.min(limit,all.length));}
function renderRetrieve(){
  const s=state.session,cs=sessionConcepts();return `<div class="study-stage-intro"><strong>Rule:</strong> answer before you look anything up. Speaking aloud is fine; the text box is optional scratch space. Then rate the retrieval, not your confidence.</div><div class="retrieval-grid">${cs.map(c=>`<article class="retrieval-card" data-concept="${esc(c.id)}"><span>${esc(c.name)}</span><h4>${esc(c.prompt)}</h4><textarea rows="4" maxlength="1800" data-retrieval-response placeholder="Write your answer, calculation, or notes here if useful.">${esc(s.responses?.[c.id]||'')}</textarea><div class="evidence-rating" aria-label="Rate retrieval for ${esc(c.name)}"><button type="button" class="${s.ratings?.[c.id]==='green'?'active':''}" data-retrieval-rate="green">Got it</button><button type="button" class="${s.ratings?.[c.id]==='yellow'?'active':''}" data-retrieval-rate="yellow">Partial</button><button type="button" class="${s.ratings?.[c.id]==='red'?'active':''}" data-retrieval-rate="red">Missed</button></div></article>`).join('')}</div>`;
}
function renderDiagnose(){
  const cs=sessionConcepts(),s=state.session,strong=cs.filter(c=>s.ratings?.[c.id]==='green'),weak=cs.filter(c=>s.ratings?.[c.id]!=='green');
  return `<div class="diagnosis-summary"><article class="diagnosis-card strong"><span>Holding</span><strong>${strong.length}</strong><p>${strong.length?strong.map(c=>esc(c.name)).join(' · '):'No concept has been demonstrated cleanly yet.'}</p></article><article class="diagnosis-card weak"><span>Repair targets</span><strong>${weak.length}</strong><p>${weak.length?weak.map(c=>esc(c.name)).join(' · '):'No repair target from this retrieval round.'}</p></article></div><section class="diagnosis-explain"><h4>What Alfred will do next</h4><p>${weak.length?'Only the Partial/Missed concepts move into targeted repair. Strong concepts stay out of the way unless they are needed for transfer practice.':'You recalled the selected concepts cleanly. The session will skip repair and use fresh application problems to check transfer.'}</p></section>`;
}
function renderRepair(){
  const s=state.session,weak=weakConcepts();if(!weak.length)return `<div class="study-pass-card"><strong>No targeted repair needed from this retrieval round.</strong><p>Move to Practice. Fresh application is a stronger check than rereading material you already recalled.</p></div>`;
  return `<div class="repair-stack">${weak.map(c=>{const guides=SG.remediationMatches?.(c.keywords||c.name,s.week)||[];const guideHtml=guides.length?`<details class="repair-study-guide"><summary>Exact CETa Study Guide repair (${guides.length})</summary>${guides.map(r=>{const p=SG.primaryPlacement?.(r),href=p?`learn.html?week=${p.week}&stage=${p.lesson===0?'ceta-lesson':'career-lesson'}&lesson=${p.lesson}&section=${encodeURIComponent(p.segment)}`:`learn.html?week=${r.week}`,err=(SG.errataFor?.(r)||[]).map(x=>`<small>⚠ ${esc(x.label)} — ${esc(x.correction)}</small>`).join('');return `<div><strong>Ch.${esc(r.chapter)} · ${esc(SG.pageLabel?.(r)||'')}</strong><span>${esc(r.focus)}</span>${err}<a class="text-link" href="${href}">Open exact Alfred teaching page →</a></div>`;}).join('')}</details>`:'';return `<article class="repair-card" data-repair-id="${esc(c.id)}"><div class="repair-card-head"><span>Repair target</span><h4>${esc(c.name)}</h4></div><p>${esc(c.repair)}</p>${c.formula?`<div class="repair-formula">${esc(c.formula)}</div>`:''}${guideHtml}<div class="repair-actions"><a class="button outline-green" href="learn.html?week=${s.week}">Open Classroom if this still does not click</a><a class="text-link" href="search.html?q=${encodeURIComponent(c.keywords||c.name)}">Find another verified explanation →</a></div><label class="repair-check"><input type="checkbox" data-repair-complete="${esc(c.id)}"${s.repairs?.[c.id]?' checked':''}><span>I reworked this concept and can state the rule in my own words.</span></label></article>`;}).join('')}</div>`;
}

function renderPractice(){
  const s=state.session,items=practiceConcepts();return `<div class="study-stage-intro"><strong>Fresh problem:</strong> predict the direction or rough size first when the problem allows it. Then solve and compare with the model.</div><div class="practice-ladder">${items.map((c,i)=>{const rec=s.practice?.[c.id]||{};return `<article class="practice-card" data-practice-id="${esc(c.id)}"><span>Practice ${i+1} · ${esc(c.name)}</span><h4>${esc(c.practice)}</h4><textarea rows="4" maxlength="1800" data-practice-response placeholder="Show the prediction, reasoning, units, or troubleshooting logic.">${esc(rec.response||'')}</textarea><details class="practice-model"><summary>Reveal model after you attempt it</summary><p>${esc(c.answer)}</p></details><div class="evidence-rating"><button type="button" class="${rec.rating==='green'?'active':''}" data-practice-rate="green">Correct / solid</button><button type="button" class="${rec.rating==='yellow'?'active':''}" data-practice-rate="yellow">Partial</button><button type="button" class="${rec.rating==='red'?'active':''}" data-practice-rate="red">Missed</button></div></article>`}).join('')}</div>`;
}
function teachBackConfig(){
  const cs=sessionConcepts();if(Number(state.session?.week)===1)return {prompt:'Teach this chain without notes: charge → current → voltage → resistance → Ohm’s law → power. Include one SI-prefix conversion and one prediction about what changes when resistance changes.',checks:['I distinguished voltage from current.','I explained at least one cause-and-effect relationship.','I used a unit/prefix correctly.','I connected the explanation to a real circuit or measurement.']};
  return {prompt:`Teach back the selected Week ${state.session?.week} concepts as one connected explanation: ${cs.map(c=>c.name).join(', ')}. Explain how at least two of them connect and give one application or measurement example.`,checks:['I explained the concepts without copying definitions.','I connected at least two ideas together.','I included a concrete application, calculation, measurement, or troubleshooting example.']};
}
function renderTeachBack(){
  const s=state.session,t=teachBackConfig(),tb=s.teachBack||{text:'',checks:{},aloud:false};return `<section class="teachback-card"><span>Teach-back</span><h4>${esc(t.prompt)}</h4><textarea id="teachback-text" rows="7" maxlength="4000" placeholder="Write your explanation here—or check the aloud option below after you say it without notes.">${esc(tb.text||'')}</textarea><label class="teachback-aloud"><input type="checkbox" id="teachback-aloud"${tb.aloud?' checked':''}><span>I completed the teach-back aloud without reading the lesson.</span></label><div class="teachback-checks">${t.checks.map((x,i)=>`<label><input type="checkbox" data-teach-check="${i}"${tb.checks?.[i]?' checked':''}><span>${esc(x)}</span></label>`).join('')}</div></section>`;
}
function finalRating(c){const p=state.session?.practice?.[c.id]?.rating;return p||state.session?.ratings?.[c.id]||'red';}
function readinessSummary(){
  const cs=sessionConcepts(),finals=Object.fromEntries(cs.map(c=>[c.id,finalRating(c)])),red=cs.filter(c=>finals[c.id]==='red'),yellow=cs.filter(c=>finals[c.id]==='yellow'),green=cs.filter(c=>finals[c.id]==='green');
  const tb=state.session?.teachBack||{},t=teachBackConfig(),teachDone=(String(tb.text||'').trim().length>=60||tb.aloud===true)&&t.checks.every((_,i)=>tb.checks?.[i]);
  return {red,yellow,green,teachDone,continueReady:red.length===0&&teachDone};
}
function renderNextMove(){
  const s=state.session,r=readinessSummary(),stage=classroomStage(s.week),weak=[...r.red,...r.yellow];
  return `<div class="next-move-grid"><article class="next-move-result ${r.continueReady?'ready':'repair'}"><span>${r.continueReady?'Ready to continue':'One more repair pass'}</span><h4>${r.continueReady?'The retrieval and transfer check support moving forward.':'The session still shows a specific gap.'}</h4><p>${r.red.length?`Missed: ${r.red.map(c=>esc(c.name)).join(', ')}. `:''}${r.yellow.length?`Partial: ${r.yellow.map(c=>esc(c.name)).join(', ')}. `:''}${!r.teachDone?'Teach-back is not complete yet.':''}</p></article><article class="next-move-result"><span>Important boundary</span><h4>Active Recall does not mark course work complete.</h4><p>This memory-check session schedules review and guides your next move. Classroom, Lab Center, and assessments remain the evidence/completion authorities.</p></article></div><div class="session-close-actions"><a class="button green" href="learn.html?week=${s.week}">${stage==='mastery'?'Return to weekly mastery':'Continue the saved Classroom stage'}</a>${weak.length?'<button type="button" class="button outline-green" id="run-focused-repair">Run another focused repair</button>':''}<a class="button outline-green" href="analytics.html">Open Mastery evidence</a></div>`;
}
function renderStageBody(){return [renderRetrieve,renderDiagnose,renderRepair,renderPractice,renderTeachBack,renderNextMove][step]?.()||'';}

function persistSession(){save();}
function setRating(id,rating){state.session.ratings=state.session.ratings||{};state.session.ratings[id]=rating;persistSession();renderSession();}
function setPracticeRating(id,rating){state.session.practice=state.session.practice||{};state.session.practice[id]={...(state.session.practice[id]||{}),rating};persistSession();renderSession();}
function validateStage(){
  const s=state.session||{};
  if(step===0){const missing=sessionConcepts().filter(c=>!s.ratings?.[c.id]);if(missing.length){alert(`Rate each retrieval first. Still unrated: ${missing.map(c=>c.name).join(', ')}`);return false;}}
  if(step===2){const missing=weakConcepts().filter(c=>!s.repairs?.[c.id]);if(missing.length){alert(`Finish the targeted repair check for: ${missing.map(c=>c.name).join(', ')}`);return false;}}
  if(step===3){const missing=practiceConcepts().filter(c=>!s.practice?.[c.id]?.rating);if(missing.length){alert(`Rate each fresh practice attempt before moving on.`);return false;}}
  if(step===4){const t=teachBackConfig(),tb=s.teachBack||{};const enough=String(tb.text||'').trim().length>=60||tb.aloud===true;const checks=t.checks.every((_,i)=>tb.checks?.[i]);if(!enough||!checks){alert('Complete the teach-back aloud or in writing, then confirm every checklist item that is truly present.');return false;}}
  return true;
}
function renderSession(){
  const s=state.session;if(!s)return;const names=sessionStageNames();step=Math.max(0,Math.min(Number(s.step)||0,names.length-1));
  $('#session-title').textContent=`Week ${String(s.week).padStart(2,'0')} · Active Recall`;$('#session-kicker').textContent=`${s.mode==='quick'?'Quick check':s.mode==='deep'?'Deep diagnostic':'Standard diagnostic'} · ${stageLabels[classroomStage(s.week)]||'Current stage'}`;
  $('#session-meta').textContent='Retrieve first. Repair only the misses. Practice with fresh problems. Finish by teaching it back.';
  $('#session-step-tabs').innerHTML=names.map((n,i)=>`<button type="button" class="${i===step?'active':''}" aria-current="${i===step?'step':'false'}" data-study-step="${i}"><span>${i+1}</span>${esc(n)}</button>`).join('');
  $('#session-progress-bar').style.width=`${((step+1)/names.length)*100}%`;$('#session-step-content').innerHTML=`<div class="step-number">Step ${step+1} of ${names.length}</div><h3>${esc(names[step])}</h3>${renderStageBody()}`;
  $('#session-prev').disabled=step===0;$('#session-next').textContent=step===names.length-1?'Close Study Session':'Next Step';
  const note=$('#session-note');if(note){note.value=s.note||'';note.oninput=()=>{state.session.note=note.value;persistSession();};}
  $$('[data-study-step]').forEach(b=>b.onclick=()=>{const dest=Number(b.dataset.studyStep);if(dest>step&&!validateStage())return;step=dest;state.session.step=step;persistSession();renderSession();});
  $$('[data-retrieval-rate]').forEach(b=>b.onclick=()=>setRating(b.closest('[data-concept]').dataset.concept,b.dataset.retrievalRate));
  $$('[data-retrieval-response]').forEach(t=>t.oninput=()=>{const id=t.closest('[data-concept]').dataset.concept;state.session.responses=state.session.responses||{};state.session.responses[id]=t.value;persistSession();});
  $$('[data-repair-complete]').forEach(c=>c.onchange=()=>{state.session.repairs=state.session.repairs||{};state.session.repairs[c.dataset.repairComplete]=c.checked;persistSession();});
  $$('[data-practice-response]').forEach(t=>t.oninput=()=>{const id=t.closest('[data-practice-id]').dataset.practiceId;state.session.practice=state.session.practice||{};state.session.practice[id]={...(state.session.practice[id]||{}),response:t.value};persistSession();});
  $$('[data-practice-rate]').forEach(b=>b.onclick=()=>setPracticeRating(b.closest('[data-practice-id]').dataset.practiceId,b.dataset.practiceRate));
  const tb=$('#teachback-text');if(tb)tb.oninput=()=>{state.session.teachBack=state.session.teachBack||{checks:{}};state.session.teachBack.text=tb.value;persistSession();};
  const aloud=$('#teachback-aloud');if(aloud)aloud.onchange=()=>{state.session.teachBack=state.session.teachBack||{checks:{}};state.session.teachBack.aloud=aloud.checked;persistSession();};
  $$('[data-teach-check]').forEach(c=>c.onchange=()=>{state.session.teachBack=state.session.teachBack||{checks:{}};state.session.teachBack.checks=state.session.teachBack.checks||{};state.session.teachBack.checks[c.dataset.teachCheck]=c.checked;persistSession();});
  $('#run-focused-repair')?.addEventListener('click',()=>{const weak=[...readinessSummary().red,...readinessSummary().yellow];startSession({forcedIds:weak.map(c=>c.id),mode:'quick'});});
}
function startSession({forcedIds=null,mode=null}={}){
  const week=currentWeek();activeMode=mode||$('input[name="session-mode"]:checked')?.value||'standard';state.defaultMode=activeMode;
  const chosen=forcedIds?.length?forcedIds.map(id=>conceptById(id,week)).filter(Boolean):chooseConcepts(week,activeMode);
  if(!chosen.length)return;
  state.lastWeek=week;state.session={version:2,week,eventId:target?.id||null,mode:activeMode,step:0,startedAt:new Date().toISOString(),conceptIds:chosen.map(c=>c.id),ratings:{},responses:{},repairs:{},practice:{},teachBack:{text:'',checks:{},aloud:false},note:''};step=0;save();
  $('#resume-session-section')?.classList.add('hidden');$('#session-workspace')?.classList.remove('hidden');document.body.classList.add('focus-mode');$('#focus-mode-toggle')?.setAttribute('aria-pressed','true');renderSession();$('#session-workspace')?.scrollIntoView({behavior:'smooth',block:'start'});
}
function renderResumeSession(){
  const box=$('#resume-session-section'),s=state.session;if(!box)return;if(!s?.conceptIds?.length){box.classList.add('hidden');return;}
  box.classList.remove('hidden');$('#resume-session-title').textContent=`Resume Week ${String(s.week).padStart(2,'0')} active recall`;$('#resume-session-copy').textContent=`You stopped at ${sessionStageNames()[Number(s.step)||0]}. Resume the memory check, or discard it and return to ordinary Study.`;
  $('#resume-session-button').onclick=()=>{$('#session-workspace').classList.remove('hidden');document.body.classList.add('focus-mode');$('#focus-mode-toggle').setAttribute('aria-pressed','true');step=Number(s.step)||0;renderSession();$('#session-workspace').scrollIntoView({behavior:'smooth',block:'start'});};
  $('#discard-session-button').onclick=()=>{state.session=null;save();renderResumeSession();renderRecommendation();};
}

function ratingInterval(r,old){if(r==='red')return 1;if(r==='yellow')return old?Math.max(2,Math.round(old*.6)):2;const ladder=[7,14,30,60,90];return ladder.find(x=>x>(old||0))||90;}
function saveWeekReview(week,id,review){
  const p=progress();p.weeks=p.weeks||{};p.recordTimes=p.recordTimes||{};const w=weekRecord(p,week);w.reviewQueue={...(w.reviewQueue||{}),[id]:review};p.weeks[week]=w;const stamp=Date.now();p.recordTimes[`week:${week}`]=stamp;p.updatedAt=new Date(stamp).toISOString();localStorage.setItem(PROGRESS_KEY,JSON.stringify(p));pushProgressRecord(`week:${week}`,w,stamp);
}
function scheduleSessionReviews(){
  const s=state.session;if(!s)return;const oldW=weekRecord(progress(),s.week),oldQ=oldW.reviewQueue||{};
  for(const c of sessionConcepts()){
    const rating=finalRating(c),key=`study:w${s.week}:${c.id}`,old=oldQ[key]||{},interval=ratingInterval(rating,Number(old.interval||0));
    saveWeekReview(s.week,key,{standardId:null,conceptId:c.id,title:c.name,prompt:c.prompt,source:'study-session-v2',interval,lastRating:rating,due:addDays(startOfDay(now()),interval).toISOString(),updatedAt:new Date().toISOString()});
  }
}
function finishSession(){
  if(!state.session)return;scheduleSessionReviews();const r=readinessSummary();state.history.unshift({week:state.session.week,eventId:state.session.eventId,mode:state.session.mode,ratings:Object.fromEntries(sessionConcepts().map(c=>[c.id,finalRating(c)])),teachBack:r.teachDone,finished:true,at:new Date().toISOString()});state.history=state.history.slice(0,100);state.session=null;save();
  $('#session-workspace')?.classList.add('hidden');document.body.classList.remove('focus-mode');$('#focus-mode-toggle')?.setAttribute('aria-pressed','false');renderResumeSession();renderRecommendation();renderReviews();renderStudyLibrary();$('#active-recall-section')?.scrollIntoView({behavior:'smooth',block:'start'});
}

function hydrateReviewsFromProgress(){const p=progress();state.reviews={};state.sessionConfidence={};Object.entries(p.events||{}).forEach(([id,v])=>{if(v?.studyReview)state.reviews[id]={...v.studyReview,eventId:Number(id)};if(v?.studyConfidence)state.sessionConfidence[id]=v.studyConfidence;});}
function saveEventStudyMeta(id,confidence,review){const p=progress();p.events=p.events||{};p.recordTimes=p.recordTimes||{};const key=String(id),stamp=Date.now();p.events[key]={...(p.events[key]||{}),studyConfidence:confidence,studyReview:review};p.recordTimes[`event:${key}`]=stamp;p.updatedAt=new Date(stamp).toISOString();localStorage.setItem(PROGRESS_KEY,JSON.stringify(p));pushProgressRecord(`event:${key}`,p.events[key],stamp);}
function reviewDue(){const t=Date.now();return Object.values(state.reviews||{}).filter(r=>Date.parse(r.due)<=t).sort((a,b)=>Date.parse(a.due)-Date.parse(b.due));}
function renderReviews(){
  const out=$('#review-queue'),eventDue=reviewDue(),conceptDue=[];if(!out)return;
  Object.entries(progress().weeks||{}).forEach(([week,w])=>Object.entries(w?.reviewQueue||{}).forEach(([id,r])=>{if(Date.parse(r.due)<=Date.now())conceptDue.push({week,id,...r});}));conceptDue.sort((a,b)=>Date.parse(a.due)-Date.parse(b.due));
  const all=[...conceptDue.map(x=>({...x,kind:'concept'})),...eventDue.map(x=>({...x,kind:'event'}))];$('#review-count').textContent=`${all.length} due`;
  if(reviewedThisBlock>=reviewLimit){out.innerHTML='<p class="review-empty">Review block complete. Continue the course, or open three more retrievals when you have capacity.</p><button type="button" class="button outline-green" id="more-reviews">Review up to 3 more</button>';$('#more-reviews').onclick=()=>{reviewLimit+=3;renderReviews();};return;}
  if(!all.length){out.innerHTML='<div class="review-empty"><strong>Nothing due right now.</strong><span>Study will schedule concepts automatically after active sessions. Mastery can also send standards here for review.</span></div>';return;}
  out.innerHTML=all.slice(0,Math.max(0,reviewLimit-reviewedThisBlock)).map(r=>r.kind==='concept'?`<article class="review-item" data-week-review="${esc(r.id)}" data-review-week="${esc(r.week)}"><span>${r.source==='study-session-v2'?'Study concept':'Competency review'} · Week ${String(r.week).padStart(2,'0')}</span><h3>${esc(r.title||r.id)}</h3><p><strong>From memory:</strong> ${esc(r.prompt||'Explain this without notes.')}</p><div><button type="button" data-week-review-rate="green">Got it</button><button type="button" data-week-review-rate="yellow">Shaky</button><button type="button" data-week-review-rate="red">Needs work</button>${r.source==='study-session-v2'?`<button type="button" class="repair-now" data-review-concept="${esc(r.conceptId||'')}">Repair now</button>`:''}</div></article>`:`<article class="review-item" data-event-review="${esc(r.eventId)}"><span>Scheduled review · Week ${String(r.week||'').padStart(2,'0')}</span><h3>${esc(r.title||'Review')}</h3><p><strong>From memory:</strong> ${esc(r.prompt||r.title||'Explain what you learned.')}</p><div><button type="button" data-event-review-rate="green">Got it</button><button type="button" data-event-review-rate="yellow">Shaky</button><button type="button" data-event-review-rate="red">Needs work</button></div></article>`).join('');
  $$('[data-week-review-rate]').forEach(b=>b.onclick=()=>{const card=b.closest('[data-week-review]'),id=card.dataset.weekReview,week=card.dataset.reviewWeek,r=weekRecord(progress(),week).reviewQueue?.[id];if(!r)return;const interval=ratingInterval(b.dataset.weekReviewRate,Number(r.interval||0));saveWeekReview(week,id,{...r,interval,lastRating:b.dataset.weekReviewRate,due:addDays(startOfDay(now()),interval).toISOString(),updatedAt:new Date().toISOString()});reviewedThisBlock++;renderReviews();});
  $$('[data-review-concept]').forEach(b=>b.onclick=()=>startSession({forcedIds:[b.dataset.reviewConcept],mode:'quick'}));
  $$('[data-event-review-rate]').forEach(b=>b.onclick=()=>{const card=b.closest('[data-event-review]'),key=card.dataset.eventReview,old=state.reviews[key];if(!old)return;old.interval=ratingInterval(b.dataset.eventReviewRate,Number(old.interval||0));old.lastRating=b.dataset.eventReviewRate;old.due=addDays(startOfDay(now()),old.interval).toISOString();old.updatedAt=new Date().toISOString();state.sessionConfidence[key]=b.dataset.eventReviewRate;saveEventStudyMeta(key,b.dataset.eventReviewRate,old);reviewedThisBlock++;renderReviews();});
}

function renderParking(){const out=$('#parking-list');if(!out)return;const list=state.parking||[];if(!list.length){out.innerHTML='<div class="review-empty"><strong>Parking lot is empty.</strong><span>Save side questions or site-improvement ideas here instead of leaving the required learning path.</span></div>';return;}out.innerHTML=list.slice().reverse().map(x=>{const site=x.kind==='site';return `<article class="parking-item${site?' site-issue-item':''}" data-parking-id="${esc(x.id)}"><div><span class="parking-kind">${site?'Site issue · fix later':'Curiosity · explore later'}</span><strong>${esc(x.text)}</strong><span>Saved ${esc(fmtDate(x.at||x.createdAt))}${x.week?` · Week ${x.week}`:''}</span></div><div>${site?'<span class="parked-builder-note">Parked for Builder Mode</span>':`<a href="search.html?q=${encodeURIComponent(x.text)}">Explore later →</a>`}<button type="button" data-remove-parking>Done</button></div></article>`}).join('');$$('[data-remove-parking]').forEach(b=>b.onclick=()=>{const id=b.closest('[data-parking-id]').dataset.parkingId;const result=window.AlfredParkingSync?.removeItem?.(state,id);if(result?.state){state=result.state;save();renderParking();if(result.record)pushProgressRecord(result.record.key,result.record.value,result.record.updatedAt);}else{state.parking=state.parking.filter(x=>x.id!==id);save();renderParking();}});}
function park(text,kind='curiosity'){const t=String(text||'').trim();if(!t)return;const result=window.AlfredParkingSync?.addItem?.(state,t,kind,currentWeek());if(result?.state){state=result.state;save();renderParking();if(result.record)pushProgressRecord(result.record.key,result.record.value,result.record.updatedAt);return;}state.parking.push({id:crypto.randomUUID?.()||String(Date.now())+Math.random(),text:t,kind,week:currentWeek(),at:new Date().toISOString()});save();renderParking();}
function installSiteIssueParking(){
  const form=$('#parking-form'),panel=form?.closest('.study-panel');if(!panel||$('#site-issue-form'))return;
  const wrap=document.createElement('div');wrap.className='site-issue-parking';wrap.innerHTML='<div class="site-issue-parking-head"><strong>Park a site issue</strong><span>Improving Alfred is not today’s coursework unless the issue blocks learning.</span></div><form id="site-issue-form"><label for="site-issue-input">Website improvement or defect to handle later</label><div><input id="site-issue-input" type="text" maxlength="500" placeholder="Example: Week 3 figure feels too small"><button class="button outline-green" type="submit">Park for Builder Mode</button></div></form>';
  panel.insertBefore(wrap,$('#parking-list'));
  $('#site-issue-form')?.addEventListener('submit',e=>{e.preventDefault();const input=$('#site-issue-input');park(input?.value,'site');if(input)input.value='';});
}
let stuckReturnFocus=null;
function openStuck(){
  stuckReturnFocus=document.activeElement;const week=state.session?.week||currentWeek(),weak=state.session?weakConcepts():[],topic=weak[0]?.name||weekData(week).topic||'current topic';$('#stuck-topic').textContent=`Current repair target: ${topic}`;
  $('#stuck-options').innerHTML=`${state.session?'<button type="button" id="jump-repair"><strong>1. Jump to targeted repair</strong><span>Go directly to the smallest gap this session identified.</span></button>':''}<a href="learn.html?week=${week}"><strong>${state.session?'2':'1'}. Return to Classroom</strong><span>Use the full lesson and worked examples when the short repair is not enough.</span></a><a href="search.html?q=${encodeURIComponent(topic)}"><strong>${state.session?'3':'2'}. Find another verified explanation</strong><span>Search the course’s verified resource layers for this exact concept.</span></a><a href="analytics.html"><strong>${state.session?'4':'3'}. Check Mastery evidence</strong><span>See whether the issue is isolated or part of a wider competency weakness.</span></a><button type="button" id="park-current-topic"><strong>${state.session?'5':'4'}. Park the side question</strong><span>Save it and return to the required objective.</span></button>`;
  const modal=$('#stuck-modal');modal.inert=false;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#jump-repair')?.addEventListener('click',()=>{step=2;state.session.step=2;save();closeStuck();renderSession();});$('#park-current-topic').onclick=()=>{park(topic);closeStuck();};requestAnimationFrame(()=>$('.modal-close',modal)?.focus());
}
function closeStuck(){const m=$('#stuck-modal');if(!m)return;m.inert=true;m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow='';stuckReturnFocus?.focus();}

function stillConnected(cfg){try{const current=JSON.parse(localStorage.getItem(SYNC_KEY)||'{}');return current.connected&&current.apiUrl===cfg.apiUrl&&current.studentKey===cfg.studentKey;}catch{return false;}}
async function pushProgressRecord(key,value,updatedAt){try{const cfg=JSON.parse(localStorage.getItem(SYNC_KEY)||'null')||{};if(!cfg.connected||!navigator.onLine||!cfg.apiUrl||!cfg.studentKey)return;let api=String(cfg.apiUrl).trim().replace(/\/+$/,'').replace(/\/(?:health|sync)$/i,'');const sk=String(cfg.studentKey).trim().toUpperCase();if(!/^https:\/\//i.test(api)||!/^AU-(?:[A-F0-9]{4}-){9}[A-F0-9]{4}$/.test(sk))return;await fetch(api+'/sync',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','Authorization':'Bearer '+sk},body:JSON.stringify({protocol:2,deviceId:cfg.deviceId||'study-page',deviceName:cfg.deviceName||'Study Page',records:[{key,value,updatedAt,deviceId:cfg.deviceId||'study-page'}]})});}catch{}}
async function syncProgressFromCloud(){try{const cfg=JSON.parse(localStorage.getItem(SYNC_KEY)||'null')||{};if(!cfg.connected||!navigator.onLine||!cfg.apiUrl||!cfg.studentKey)return;let api=String(cfg.apiUrl).trim().replace(/\/+$/,'').replace(/\/(?:health|sync)$/i,'');const sk=String(cfg.studentKey).trim().toUpperCase();if(!/^https:\/\//i.test(api)||!/^AU-(?:[A-F0-9]{4}-){9}[A-F0-9]{4}$/.test(sk))return;let p=progress(),records=[],did=cfg.deviceId||'study-page';const add=(key,value)=>{const updatedAt=Number(p.recordTimes?.[key]||0);if(updatedAt>0)records.push({key,value,updatedAt,deviceId:did});};Object.entries(p.events||{}).forEach(([id,v])=>add(`event:${id}`,v));Object.entries(p.weeks||{}).forEach(([w,v])=>add(`week:${w}`,v));records.push(...(window.AlfredParkingSync?.recordsFromState?.(state,did)||[]));const res=await fetch(api+'/sync',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','Authorization':'Bearer '+sk},body:JSON.stringify({protocol:2,deviceId:did,deviceName:cfg.deviceName||'Study Page',records})});if(!res.ok)return;const data=await res.json();if(!stillConnected(cfg))return;p=progress();p.events=p.events||{};p.weeks=p.weeks||{};p.recordTimes=p.recordTimes||{};(data.records||[]).forEach(r=>{const lt=Number(p.recordTimes[r.key]||0),ct=Number(r.updatedAt||0);if(ct<lt)return;if(r.key.startsWith('event:'))p.events[r.key.slice(6)]=window.AlfredState?.normalizeEvent?.(r.value)||r.value||{};else if(r.key.startsWith('week:'))p.weeks[r.key.slice(5)]=r.value;else return;p.recordTimes[r.key]=ct;});p.updatedAt=new Date().toISOString();localStorage.setItem(PROGRESS_KEY,JSON.stringify(p));const parkingMerge=window.AlfredParkingSync?.applyRecords?.(state,data.records||[]);if(parkingMerge?.changed){state=parkingMerge.state;save();renderParking();}hydrateReviewsFromProgress();renderRecommendation();renderWeeklyPlan();renderReviews();renderStudyLibrary();}catch{}}

function applyQuiet(){const on=localStorage.getItem(QUIET_KEY)==='1';document.body.classList.toggle('quiet-mode',on);$('#quiet-mode-toggle')?.setAttribute('aria-pressed',String(on));}
function toggleQuiet(){const on=localStorage.getItem(QUIET_KEY)!=='1';localStorage.setItem(QUIET_KEY,on?'1':'0');applyQuiet();}
function toggleFocus(){const on=!document.body.classList.contains('focus-mode');if(on&&$('#session-workspace')?.classList.contains('hidden')){setLibraryView('recall');$('#active-recall-section')?.scrollIntoView({behavior:'smooth',block:'start'});return;}document.body.classList.toggle('focus-mode',on);$('#focus-mode-toggle')?.setAttribute('aria-pressed',String(on));if(on)$('#session-workspace')?.scrollIntoView({behavior:'smooth'});}
function rewriteStaticCopy(){
  const panel=$('#study-support-area .panel-intro');if(panel)panel.textContent='These scheduled memory checks are available when you want them. They never block Review Material, Flashcards, Watch & Review, or Reference.';
}


const initialView=new URLSearchParams(location.search).get('view');if(['review','flashcards','media','reference','weak','recall'].includes(initialView))state.library.view=initialView;
state.lastWeek=currentWeek();save();
hydrateReviewsFromProgress();rewriteStaticCopy();installSiteIssueParking();renderRecommendation();renderWeeklyPlan();renderReviews();renderParking();renderResumeSession();renderStudyLibrary();if(state.session?.conceptIds?.length&&location.hash==='#session-workspace')$('#resume-session-button')?.click();applyQuiet();syncProgressFromCloud();
window.addEventListener('online',syncProgressFromCloud);window.addEventListener('storage',e=>{if(e.key===PROGRESS_KEY){hydrateReviewsFromProgress();renderRecommendation();renderReviews();renderStudyLibrary();}if(e.key===STUDY_KEY){state=load();renderResumeSession();renderParking();renderStudyLibrary();}});window.addEventListener('alfred-parking-updated',()=>{state=load();renderParking();});
$$('input[name="session-mode"]').forEach(r=>{r.checked=r.value===activeMode});
$$('[data-study-view]').forEach(b=>b.addEventListener('click',()=>setLibraryView(b.dataset.studyView)));
$('#back-to-study-library')?.addEventListener('click',()=>{setLibraryView('review');$('#study-library-section')?.scrollIntoView({behavior:'smooth',block:'start'});});
$('#start-study-session')?.addEventListener('click',e=>{const href=e.currentTarget?.dataset?.routeHref;if(href){location.href=href;return;}startSession();});$('#quiet-mode-toggle')?.addEventListener('click',toggleQuiet);$('#focus-mode-toggle')?.addEventListener('click',toggleFocus);$('#leave-focus')?.addEventListener('click',()=>{document.body.classList.remove('focus-mode');$('#focus-mode-toggle')?.setAttribute('aria-pressed','false');});
$('#session-prev')?.addEventListener('click',()=>{if(step>0){step--;state.session.step=step;save();renderSession();}});$('#session-next')?.addEventListener('click',()=>{const names=sessionStageNames();if(step<names.length-1){if(!validateStage())return;step++;state.session.step=step;save();renderSession();}else finishSession();});
$('#session-help')?.addEventListener('click',openStuck);$('#parking-form')?.addEventListener('submit',e=>{e.preventDefault();park($('#parking-input')?.value);if($('#parking-input'))$('#parking-input').value='';});
if($('#stuck-modal'))$('#stuck-modal').inert=true;$$('[data-close-stuck]').forEach(x=>x.onclick=closeStuck);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#stuck-modal')?.classList.contains('open'))closeStuck();});
})();
