/* v16.3.74 Week 2 Career mastery balance for assessment-only pages. */
(()=>{
  const AS=window.ALFRED_ASSESSMENT;
  if(!AS?.questions)return;
  const q=(id,prompt,choices,answer,explanation,skill,section,title,standards)=>({id,track:'Career',standards,prompt,choices,answer,explanation,difficulty:'Foundation',kind:'MCQ',skill,questionClass:'substantive',masteryEvidence:true,evidenceWeight:0.7,sourceRef:'Alfred Week 2 Career v16.3.74',minWeek:2,family:`v16374-${id}`,reviewSectionId:section,reviewSectionTitle:title,reviewStandardCodes:standards.map(s=>s.replace('CAREER:','')),reviewConcept:'Week 2 Career troubleshooting',reviewRouteVersion:'16.3.74',audit:{status:'week2-career-v16.3.74-reviewed',date:'2026-09-28',note:'Original Alfred scenario aligned to the remediated Career lesson; not an official ETA item.',sources:[{title:'Alfred Week 2 Career remediation',url:'',locator:section}]}});
  const add=[
    q('CQ1204','A 10 V divider should have a 5 V midpoint. Before probing, what is the strongest troubleshooting habit?',['Measure random nodes until one looks strange','Write the expected source/midpoint values and what each possible result would imply','Replace both resistors','Measure resistance while the circuit is powered'],1,'Prediction turns each measurement into evidence and determines what the result means.','Application','career-w02-predict-before-measuring','Predict before measuring',['CAREER:C2.1','CAREER:C3.1']),
    q('CQ1205','A series path is open. Which signature is most consistent with that fault?',['Current through the path tends toward zero and a large voltage can appear across the break','Voltage across the break must be exactly zero','Every node must become the source voltage','Resistance to ground must always be zero'],0,'An open interrupts current; the source can place a substantial potential difference across the break.','Understanding','career-w02-fault-signatures','Learn the signatures of common faults',['CAREER:C2.4','CAREER:C5.1']),
    q('CQ1206','Source and node A match predictions, but the immediately downstream node B does not. What should you do next?',['Treat A as last known good, B as first known bad, and concentrate on the boundary/load/reference around B','Replace the supply','Ignore A and start over at a random node','Assume node A is the fault because it was measured first'],0,'The last-good / first-bad boundary narrows the region without claiming every upstream detail is permanently proven.','Application','career-w02-last-good-first-bad','Find the last good point and the first bad point',['CAREER:C2.6','CAREER:C5.1']),
    q('CQ1207','Vout is 0 V under three hypotheses: open upper resistor, output short, or missing source. Which test has the LEAST information value?',['Measure Vout again','Measure source-side voltage','Power off and measure Vout-to-ground resistance','Compare voltage on both sides of the upper resistor'],0,'All three hypotheses already predict 0 V at Vout, so repeating that measurement barely separates them.','Application','career-w02-discriminating-measurement','Choose one measurement that separates hypotheses',['CAREER:C5.2','CAREER:C3.1']),
    q('CQ1208','After repairing a suspected connector-side short, what is the strongest verification?',['Stop as soon as the board powers on','Repeat the original failing measurement, then run one nearby regression check','Replace another component just in case','Delete the original readings so the record is cleaner'],1,'Verification must directly retest the original failure and check that the repair did not create a nearby problem.','Application','career-w02-change-one-verify','Change one thing, verify the repair, and preserve the evidence',['CAREER:C5.3','CAREER:C2.1']),
    q('CQ1209','Why is changing several components and wires at once weak troubleshooting practice?',['It makes the circuit too visually simple','A successful result no longer tells you which change actually corrected the fault','It always violates Ohm’s law','It prevents any voltage measurement from being taken'],1,'One-variable changes preserve causal evidence between the diagnosis, repair, and verification.','Understanding','career-w02-change-one-verify','Change one thing, verify the repair, and preserve the evidence',['CAREER:C5.2','CAREER:C5.3'])
  ];
  const ids=new Set(add.map(x=>x.id));AS.questions=AS.questions.filter(x=>!ids.has(x.id));AS.questions.push(...add);
  const test=(AS.weeklyTests||[]).find(x=>+x.week===2);
  if(test){test.title='Week 02 Mastery — DC Networks + Technician Troubleshooting';test.career=['C2.1','C2.4','C2.6','C3.1','C5.1','C5.2','C5.3'];test.count=12;test.mix={CETa:6,Career:6};test.target=80;test.questionIds=['CQ1067','CQ1068','CQ0312','CQ0316','CQ1088','CQ0290','CQ1204','CQ1205','CQ1206','CQ1207','CQ1208','CQ1209'];test.alignment='Balanced Week 2 mastery: six circuit-analysis questions and six technician-troubleshooting questions. CETa and Career are co-equal evidence tracks.';test.optional=true;}
  if(AS.meta){AS.meta.questionCount=AS.questions.length;AS.meta.cetaQuestionCount=AS.questions.filter(x=>x.track==='CETa').length;AS.meta.careerQuestionCount=AS.questions.filter(x=>x.track==='Career').length;}
})();
